### ISSUE TITLE
Design: Move the Bulk Uploader to General Settings

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther#1035]
### Describe the ideal solution

Moving the bulk uploader into a single place (general settings) to avoid confusion. This approach also stays in line with the pattern we have set forth on the 'global module', where settings that apply to both Rules and Policies live in one place.

### Describe your use cases

Right now, it's normal to zip together rules and policies into a single package. When uploading today, it's slightly misleading since we do not get a breakdown of updated globals, rules, and policies in the UI. After chatting with @nhakmiller, we agreed this would be a good iteration.

### How frequently would you use such feature

Daily

### Describe alternatives you have considered

CLI and current uploader.

### References

None

**Comment by 3nvi** [comment]
I'm increasing the estimate on this, since we have to create a separate page for it (currently  it's a modal).

Should the uploader be a single place for both rules & policies, or  should they  be separate  pages?

**Comment by jacknagz** [comment]
> Should the uploader be a single place for both rules & policies, or should they be separate pages?

It should be a single page. When you upload a package, it should show the same breakdown you would get from the CLI's `upload` command:

```
{
  "modifiedGlobals": 1,
  "modifiedPolicies": 71,
  "modifiedRules": 30,
  "newGlobals": 1,
  "newPolicies": 0,
  "newRules": 6,
  "totalGlobals": 2,
  "totalPolicies": 71,
  "totalRules": 44
}
```

**Comment by 3nvi** [comment]
oooh you meant a single place to upload everything. Sorry  in my mind, each had their own dedicated button.

Sure thing!

**Comment by 3nvi** [comment]
For @dimitriszoitas:

The functionality we want to migrate has to do  with what happens when you click "Create Rule" or "Create Policy".  Currently there  is a dropdown with the option to create  a single one or bulk  upload some.

Jack proposes a single place (diff page) for **both** rules, policies & python modules, where users can upload a zip file (as today) and we can parse it and create rules/policies out of it.

The response we get from the API (and  thus the data we can show) can be seen In Jack's comment above. Essentially we can get how many were created & modified from each category

**Comment by dimitriszoitas** [comment]
@3nvi Please review the mockups found in [this collection](https://share.goabstract.com/64c1d8ca-7c01-4213-835c-a9e89c4d05cd)

**Comment by 3nvi** [comment]
Looks great @dimitriszoitas
