### ISSUE TITLE
[Feature] Allow User Updates 

### ISSUE THREAD

**Issue by 3nvi** [panther-labs/panther#107]
**Is your feature request related to a problem? Please describe.**
Platform should allow to update the details of a user. Currently, the system only allows you to invite & delete users, but not to update them.

An example of that would be a typo in their name or email.

**Describe the solution you'd like**
Platform should allow user updates

**Comment by 3nvi** [comment]
@austinbyers Is there any work related to that that needs to be executed in the backend? If the user has just been invited, perhaps we need to re-send an email if his email is changed

**Comment by austinbyers** [comment]
A user can already update their own first/last name - I just tried with a fresh deployment. Is this issue referring to updating names for other users as well?

We do not allow updating the email address, which was a conscious decision at the time because (a) the `panther-users` Dynamo table is keyed by email address and (b) many security products do not allow you to change email addresses once a user is created (you just delete the user and add a new one).

I believe the frontend sends Cognito userIDs in API calls, so as far as I know updating email is technically feasible. A typo in the email would be fixed before a user could even sign in (since they wouldn't get credentials otherwise), do we feel it's important to be able to update the email?

**Comment by austinbyers** [comment]
As part of the users-api redesign, I'll make sure we allow:

- Updating user name (already possible)
- Updating user email (I think already possible in the backend, but not tested)
- Change role (enterprise edition)
- Reset password

**Comment by austinbyers** [comment]
I've confirmed that as of v0.3.0, you can

- Change first/last name
- Change email
- Reset password

For any user. So there's nothing blocking this in the backend

**Comment by alexmylonas** [comment]
@austinbyers What's the process for changing emails? Do users get a confirmation email on last email or just a prompt on new email?
