### ISSUE TITLE
Allow filtering of Rules based on Creator

### ISSUE THREAD

**Issue by 3nvi** [panther-labs/panther#1078]
### Describe the ideal solution

Currently, rules  can be filtered  by many fields, but it's still hard to know who added what. Specifically, Panther has a lot of pre-created rules, but users can also add their own. Rules created by Panther itself co-exist  with the ones created by the users themselves, so we need a way to filter based on whether the role was autogenerated or not.

As a first step, we should allow to quickly filter based on  whether the rule was created by Panther or not. If that  turns out to be easy, we can also enhance this functionality by allowing filtering for each individual user.

The exact same thing needs to happen for the Policies page (in Cloud Security)

### Describe your use cases

Organizations want to see what they themselves have added VS what was already there

### How frequently would you use such feature

Weekly

### Describe alternatives you have considered

Alternatives is to sort  by creation date. The rules at the "top" are the custom ones, created by members of the organization

### Additional context

I personally  think that the quickest & biggest value will be created by providing a simple filter to separate organization-created Rules vs Panther pre-created rules. Filtering by individual users is nice, but can **potentially** be added later down the line.

**Comment by 3nvi** [comment]
@jacknagz that was feedback from users. Would you like to plan it for a release or added to product board?

**Comment by austinbyers** [comment]
So there are two components to this:

1. Filter rules/policies created (or not) by the system
2. Filter rules/policies created by a specific user

In the backend, these are the same - if the `createdBy` is the system ID (`00000000-0000-4000-8000-000000000000`), we know it was created by Panther during the initial deployment.

It is not sufficient to just add a `createdBy` filter, since that doesn't give an easy way to filter *out* the system rules. So we'll add the following:

```go
// The same fields will be added to ListPolicies and ListRules
type ListPoliciesInput struct {
    // ... existing filter fields... 

    // Only include policies whose creator matches this user ID (which need not be a uuid)
    CreatedBy string `json:"createdBy"`

    // Only include policies which were last modified by this user ID
    LastModifiedBy string `json:"lastModifiedBy"`

    // If True, include only policies which were created by the system during the initial deployment
    // If False, include only policies where were NOT created by the system during the initial deployment
    InitialSet *bool `json:"initialSet"`
}
```

----

@AlexPanther the implementation outline is as follows:

1. Add those new fields to `ListPoliciesInput` and `ListRulesInput` Go structs
2. Implement these filters in the backend by adding them to the Dynamo filter expression
    - If `*InitialSet == True`, you will want to add a filter for `createdBy = "00000000-0000-4000-8000-000000000000"`
    - If `*InitialSet == False`, you will want to add a filter for `createdBy != "00000000-0000-4000-8000-000000000000"`
    - If `InitialSet` is nil (not defined), do nothing. It will behave similarly to the `Enabled` filter
3. Add integration tests which filter by creator / last modified / not in the initial set
4. Add those new fields to the input structs of the same name in the GraphQL schema

----

The frontend implementation will need to be a separate task because they will need to show the available user *names*, but send the ID to the backend for filtering

**Comment by 3nvi** [comment]
Initially I think that just being able to filter our what Panther has created vs what has been created manually is enough for now. I don't know if we still consider this a priority  6 months later, but perhaps @mattthetraveler can help out here.

**Comment by mattthetraveler** [comment]
Let's keep priority where it is and see if we can squeeze it into an upcoming sprint!

**Comment by austinbyers** [comment]
Agreed that this is not high priority. But the backend change was easy, so we've implemented it. You can now filter by default rules, or excluding default rules, or you can filter to a specific createdBy or lastModifiedBy author.

Since the backend is done, I'm re-assigning the issue to @3nvi and the web team as a low priority task.

----

I believe there is ongoing planning for official "rule pack" management, so perhaps the frontend for this should wait until we design how rule packs will work
