### ISSUE TITLE
Bulk upload doesn't validate unique test names

### ISSUE THREAD

**Issue by s0l0ist** [panther-labs/panther#1142]
### Describe the bug

When a bulk upload API is called, we begin to validate the Rules/Policies; however, there is no validation for **unique** test names. This allows the user to accidentally upload a Rule/Policy containing multiple tests with the same name resulting in the `edit` page of a Rule/Policy to disable the `Update` button rendering the user unable to modify the object.

There is a workaround that is not obvious:
- In the Panther UI, navigate to the Rule/Policy that is affected
- Notice the tests that have the same name
- Click on the one of the tests and update the name
- The `Update` button should become enabled and allow you to save

### Steps to reproduce

1. Create a rule or policy with at least two tests that have the same name
2. Use the CLI tool to upload
3. Navigate to the troubled rule or policy and click `Edit`
4. Notice the form doesn't disable the `Update` button, rendering it impossible to update.

### Expected behavior

Bulk uploads should error on tests with the same name inside the scope of a single Rule/Policy.

### Environment

Latest master

### Additional context

N/A

### Screenshots

![Screen Shot 2020-07-08 at 5.58.33 PM.png](https://images.zenhubusercontent.com/5ed67791600f3c2676518383/90e5d87d-657e-492f-ba26-a01c7b0ed752)

**Comment by nhakmiller** [comment]
Interesting perspective. I think it's important to decide what system is responsible for defining the expected behavior, the rest of the backend accepts tests without unique names so is it an issue with the bulk upload for not flagging these as an issue, or an issue with the frontend for enforcing a standard that doesn't exist anywhere else? Functionally speaking, do test names need to be unique? I just glanced at the policy/rule testing code real quick, it does not require/rely on unique naming of tests either as far as I can tell. If we decide that policy/rule test names should be unique, we should enforce that everywhere. It seems intuitive that unique policy/rule test names are required, but at the same time I don't see it adding any actual benefit to correctness/usability of the product.

**Comment by austinbyers** [comment]
> Functionally speaking, do test names need to be unique?

Not exactly - the backend only cares about the [test index](https://github.com/panther-labs/panther/blob/master/internal/core/analysis_api/handlers/test_policy.go#L89-L91) when evaluating. However, the results are [reported by test name](https://github.com/panther-labs/panther/blob/master/api/gateway/analysis/models/test_error_result.go#L31-L41)

It would certainly be confusing to have more than one test with the same name when they could have different results.

So I'd agree that we should enforce uniqueness.

> If we decide that policy/rule test names should be unique, we should enforce that everywhere.

Yes - this would actually be a check when creating any policy

**Comment by austinbyers** [comment]
It's worth noting that we enforce policy/rule name uniqueness for the same reason - the backend only cares about the ID, but we prevent duplicate names to avoid confusion for the user

**Comment by nhakmiller** [comment]
> > Functionally speaking, do test names need to be unique?
> 
> Not exactly - the backend only cares about the [test index](https://github.com/panther-labs/panther/blob/master/internal/core/analysis_api/handlers/test_policy.go#L89-L91) when evaluating. However, the results are [reported by test name](https://github.com/panther-labs/panther/blob/master/api/gateway/analysis/models/test_error_result.go#L31-L41)

It was a rhetorical question :P

What I'm getting at is fixing it by removing the frontend validation:
- Remove validation in update policy/rule UI
- Remove validation in create update/rule UI

Fixing it by adding backend validation:
- Add validation in Create policy/rule endpoints
- Add validation in Update policy/rule endpoints
- Add validation in panther_analysis_tool
- Add validation in BulkUpload endpoint

Seems like more work in the latter. I don't really care either way, just seems like a very low priority that I don't think I could justify spending time on. But we can just leave the issue open in the backlog and get to it someday I suppose.

**Comment by austinbyers** [comment]
The validation should be in the backend so that it runs when we BulkUpload, e.g. with the `panther-analysis-tool`. That is what caused this specific issue - our own rule packs had duplicate tests, which frontend validation alone could not have caught.

The check would run for all policy changes - Create/Update/BulkUpload, like you say. Honestly, that should be a pretty easy change. Adding it to the CLI tool is also nice but not strictly required - the API call to upload the packs would fail.

@giorgosp will be taking this issue since he's been working in that area of the codebase recently. Thanks George!

**Comment by nhakmiller** [comment]
I was saying we should remove the frontend validation, not add more. I would say our rule packs having duplicate tests is not what caused this issue. What caused this issue is that the frontend is incorrectly trying to apply validation on something that doesn't need to be validated.

If we do enforce this validation, I think the analysis tool should be updated in addition to the backend because the `test` functionality of the analysis tool does not talk to Panther at all intentionally so that it can be run without credentials/access to Panther. It would not be very good for the tool to say all schemas are validated and tests are passing but then have the bulk upload fail.

**Comment by giorgosp** [comment]
I would also vote disabling the validation on the UI. Most often they won't create tests with duplicate names, so validating that would be very low priority. It would be very important, though, in case we used these names as the id of the tests, which seems we do not.

**Comment by austinbyers** [comment]
> I would also vote disabling the validation on the UI.

Agreed! Sorry if I didn't make that clear. The frontend should only be doing very basic checks, this does not need to be one of them

**Comment by s0l0ist** [comment]
I've quickly gone in and fixed this in the frontend.
