### ISSUE TITLE
Design: Log Analysis Failure display

### ISSUE THREAD

**Issue by 3nvi** [panther-labs/panther#1172]
### Description

This design should cover the following:

1) Display errors that occur when running rules

As you know, we define rules, they run against logs and they produce alerts in case of a "match".

Sometimes though, exceptions occur and when we try to run a rule against a particular log entry (from now on: **Event**), things go bad and exceptions are raised. These exceptions don't mean that an Alert should be created since it means that either the user wrote "bad python" or Panther raised has some "internal bug".

This ticket  has to do with how we display that to the user

### Acceptance Criteria

- The rule should display an error status if errors have been generated in the last 15(?) minutes
- Rule error messages should be available in a tab in the Rule Overview
- The error tab should display the error message, a recent event that failed against the rule, and a date/time of last error
- The total error count should also be displayed

I'll defer to @kostaspap on additional details.

### Additional Context

Basic wireframe idea:

| Error Message | Error Count | Last Error Time |
|:--------------:|-------------|-----------------|
| ` KeyError('errorCode')` | 50 | 11:23:33 July 27th, 2020 <> (Click to expand)|

**Comment by 3nvi** [comment]
@kostaspap please also validate that the acceptance criteria are correct

**Comment by dimitriszoitas** [comment]
I am going to need more context and content for this issue. Firstly, I believe that we are going to have to change the layout of the Rule Detail Page to be aligned with the (soon to be changed) Alert Detail Page (with tabs). Are we going to have a tab specific for these "failures" described in the issue?

**Comment by dimitriszoitas** [comment]
I will be needing some feedback on this because I'm working on the detail pages atm

**Comment by 3nvi** [comment]
I'm adding @kostaspap as a assignee

**Comment by dimitriszoitas** [comment]
[Here](https://share.goabstract.com/47e686c6-f1da-4500-9387-c0ca4917fd6f?collectionLayerId=eda90eb3-d696-4f6d-9fec-9e2c4d3e6d55&mode=design) you can find a collection with the rule's detail page. I've got an "error" tab where I will display somehow the requested items from this issue.

What I would like to know is:

1. What information should be displayed in each error/failure (I need to know this so that I can design a table or another kind of component)
2. Should the json/csv/tsv/whatever be displayd inline/inscreen/in a modal/be downloaded as a file

**Comment by jacknagz** [comment]
@dimitriszoitas @3nvi @kostaspap updated the acceptance criteria

**Comment by dimitriszoitas** [comment]
I've commited the updated mockups in [this link](https://app.abstract.com/projects/558a8de6-7134-4c8b-91c5-62074bb1279b/branches/849670d3-62c0-462f-b399-bf6174c4352b/commits/e2089cfe76d5d046dc4577d3b235b9a6b7b994c8/files/3cc6ad23-a286-4d07-a10b-a9852419c176/layers/2968E7EC-5DF5-4DC9-9532-5FC025FDE826?collectionId=e1ea6de7-39a9-46a1-9f20-a2fa3c7fa4be&collectionLayerId=eda90eb3-d696-4f6d-9fec-9e2c4d3e6d55&mode=design)

**Comment by dimitriszoitas** [comment]
After syncing with @kostaspap I made changes to the rules pages overall. You can find the collection [here](https://share.goabstract.com/2ef994dd-57f0-42dd-9228-4abb0fe86a05)

To sum up the changes:

1. In the rules overview page I facelifted the bar charts to be aligned with the Alerts Overview
2. In the overview page, I replaced the rules table with cards, and also added Total Events and Total Errors in each Rule. Kostas explained that the error is not "tied" to the rule, but may occur due to input that may create an error but it won necessarily be permanent.
3. I created the component for the errors in the rule details page

**Comment by kostaspap** [comment]
@rleighton and @jacknagz please take a look at the designs above and leave your comments in Abstract.
