### ISSUE TITLE
Frontend should retrieve the list of available log types by querying 

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther#1282]
### Description

The list of log types used by frontend is currently defined as a list of constants. We need to modify FE to retrieve the list of log types by querying the appropriate backend API. 

### Acceptance Criteria

- Frontend queries backend to retrieve the list of **deployed** log types during source onboarding/editing and rule creation/editing.

**Comment by 3nvi** [comment]
@kostaspap Is this something that we should have for 1.8? 

CC @rleighton

**Comment by kostaspap** [comment]
> @kostaspap Is this something that we should have for 1.8?
> 
> CC @rleighton

@alxarch is owning the epic. @alxarch , I believe this should be in for 1.8?

**Comment by rleighton** [comment]
It would be nice but this is not currently a big issue.

**Comment by kostaspap** [comment]
> It would be nice but this is not currently a big issue.

It will be required for custom log types since the log types can be created/deleted during runtime.

**Comment by 3nvi** [comment]
Since we are going to go this way, I'll need to increase the scope of the related work to also include a breakdown of which log maps to which service.

Given the designs [here](https://app.abstract.com/projects/558a8de6-7134-4c8b-91c5-62074bb1279b/branches/849670d3-62c0-462f-b399-bf6174c4352b/collections/eddb711d-3691-4e4f-ba4d-6eb04ff9a773), you can see that the onboarding has

**Step 1**
Select  a Service

**Step 2**
Select  a Transport method

**Step 3**
Show the service's form with the log types prefilled

Currently, the log types are static, so I know which log types map to which service. Once  they are dynamic I can't  do that, so I'll need an API to return to me a list of log types for a particular service that I query.

Is that ok?

**Comment by 3nvi** [comment]
Agreed with Kostas & Alex that for now, this can be implemented  statically in the Front-end, thus the API will just need to provide a list of strings
