### ISSUE TITLE
p_any_usernames and p_any_emails

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther#1321]
### Describe the ideal solution

New standard fields for usernames and email addresses to make writing rules quicker, primarily for SaaS logs.

### References

Some sample mappings below (not comprehensive):

GSuite.Reports => actor['email']
AWS.CloudTrail => userIdentity['userName']
OneLogin.Events => user_name
GitLab.Production and API => username

### Additional context

Let's prioritize the SaaS-based logs, then move on to the Cloud/Host logs.

**Comment by kostaspap** [comment]
How do we treat the scenario where a username is also an email? Do we add it in both?

**Comment by alxarch** [comment]
> How do we treat the scenario where a username is also an email? Do we add it in both? @jacknagz @rleighton

Since we allow the schemas to specify multiple indicator scanners this should be on a per-logtype basis by adding *both* scanners to the string.

**Comment by rleighton** [comment]
I would add to both

**Comment by jacknagz** [comment]
I would actually say that we should adhere to strict formats for standard fields, meaning we would not put emails as usernames. Similarly, a hostname should not be classified as a domain.

**Comment by rleighton** [comment]
Except they can legit be both

**Comment by alxarch** [comment]
As a general approach I would avoid a strict check for a value conforming email format. The purpose of the log processor is not to validate the log output. We could end up failing to read data because of a bug in external software or misconfiguration of a server. It is preferable to do minimal checking and such 'mistakes' would end up in query results, potentially helping with detecting abnormal behavior.

If the user marks a field as `panther:"email"` for example, it is not our job to throw an error if the field is not a valid email address. We can still have some sort of fast check (i.e. `contains('@')`) to avoid adding completely invalid input, but I would avoid using a complex regular expression or similar slow processing to check an email value. IMO an invalid email showing up in rules,queries,indicator searches woulg **help** users detect abnormal behavior. Users would be blind to this if we just drop the values.

**Comment by kostaspap** [comment]
> As a general approach I would avoid a strict check for a value conforming email format. The purpose of the log processor is not to validate the log output. We could end up failing to read data because of a bug in external software or misconfiguration of a server. It is preferable to do minimal checking and such 'mistakes' would end up in query results, potentially helping with detecting abnormal behavior.
> 
> If the user marks a field as `panther:"email"` for example, it is not our job to throw an error if the field is not a valid email address. We can still have some sort of fast check (i.e. `notEmpty` or even `contains('@')`) to avoid adding completely invalid input, but I would avoid using a complex regular expression or similar slow processing to check an email value. IMO an invalid email showing up in rules,queries,indicator searches woulg **help** users detect abnormal behavior. Users would be blind to this if we just drop the values.

I think for email, the only checks we need to do are the ones that you mention: check that the string is not empty and that the character `@` appears in there

**Comment by kostaspap** [comment]
We need to make sure before closing this PR that: 
1. panther_views tables contain the new fields
2. The new fields are searchable through Indicator search

**Comment by rleighton** [comment]
Also add to documentation
