### ISSUE TITLE
List Alert Colors and Columns Improvement

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther#1344]
### Describe the current solution

Currently, the alert status of Open catches user attention too much, and we should consider using softer colors (see screenshot). 

### Describe the ideal solution

- [ ] Use softer colors for the alert status so it's not pronounced over the severity
- [ ] Adjust the column order: severity, status, alert title, alert ID, view rule, created at, num events

### Additional context

![Screen Shot 2020-08-11 at 8.25.01 AM.png](https://images.zenhubusercontent.com/5e5006ddf054a9e90b62b812/e503b34e-cfb1-4dd4-ad56-b7d334bc2ce3)

**Comment by dimitriszoitas** [comment]
I have created a collection for the alerts flow [here](https://share.goabstract.com/0ea8bda4-2320-42a7-9106-bcb6e5387da7)

I've also revised the alerts overview page with the following:

1. Changed the layout of the top component that we had in tha same view the alerts by severity and the alerts by tag and put them in a card with two tabs. I kept separately a card with the total alerts.

2. I also changed the table layout that we are using for the alerts, and designed a card component for this, since we're slowly transferring to that kind of logic. It gives us more flexibility to add content if needed and the alert message shows clearly.

@jacknagz and @3nvi please let me know what you think

**Comment by 3nvi** [comment]
Left my comments.

Just a small one about bar chart thickness. Other than that it looks really nice to me

**Comment by 3nvi** [comment]
Requirements satisfied
