### ISSUE TITLE
mage teardown

### ISSUE THREAD

**Issue by austinbyers** [panther-labs/panther#135]
**Is your feature request related to a problem? Please describe.**
Tearing down a Panther deployment requires several manual steps before the CloudFormation stacks can be deleted:

- Empty all panther S3 buckets
- Teardown the web cluster
- Delete panther-app and panther-app-frontend stacks
- Delete panther-buckets stack

Sometimes, CloudWatch log groups are also not deleted even when the stack is deleted, because leftover Lambda invocations are still writing logs. In this case, the next deployment will fail because the log group already exists.

Also, self-signed ACM certificates are created manually and will remain even after deleting the CloudFormation stacks.

**Describe the solution you'd like**
Add a `mage teardown` command that will, after user confirmation, orchestrate the deletion of all Panther resources

**Describe alternatives you've considered**
Doing it by hand is annoying and wastes developer cycles when we inevitably forget one of the steps

**Comment by kostaspap** [comment]
Is this really a problem? Should we really spend developer cycle for this? 

In my personal experience, the problem was never the tearing down the infrastructure was slow. The biggest problem that comes with tearing down the infrastructure is that we then need to setup everything once again. Deploying the stack could take several minutes, then it takes long time to setup compliance for accounts, log processing for log sources and destinations.

**Comment by austinbyers** [comment]
> Is this really a problem? Should we really spend developer cycle for this?

It's not high priority at the moment (I didn't mean to assign it to the v0.3 milestone), but absolutely worth doing. It will only take maybe a day of work. @3nvi and @nhakmiller have both asked for such a feature, and I spend ~30 minutes a day tearing down deployments. (I'm constantly tearing down and redeploying)

Plus, it guarantees that a user can completely remove a Panther deployment. There are artifacts right now that are left behind even if the CloudFormation stacks are deleted (ACM certificates, log groups)

**Comment by nhakmiller** [comment]
There some artifacts that are left because they are not controlled by CloudFormation (ACM Certificates), and some that are left because the are controlled by CFN but are protected against deletion (S3 buckets), and some that left because they are controlled by CFN and can be deleted but after CFN deletes them they get referenced and then re-created which CFN doesn't know about (log groups). Due to the complexity here, I think it is worth a dedicated command. I agree this is not a high priority (not needed before V1), but I think it is needed eventually because it:

1. Provides developers with an easier way to test fresh deployments
2. Provides customers with an easier way to "uninstall" panther if they decide they don't want to use it

Of course we're not planning around case 2 being a major concern (who would ever want to uninstall right 😄) but I think it is also an important consideration as part of a mature product. It also helps with people who want to do a test deployment in a development account, then blow the test deployment away and do a real deployment in a production account after seeing the value.

Again, not a priority for v1, but definitely a consideration at some point imo.

**Comment by 3nvi** [comment]
> > Is this really a problem? Should we really spend developer cycle for this?
> 
> It's not high priority at the moment (I didn't mean to assign it to the v0.3 milestone), but absolutely worth doing. It will only take maybe a day of work. @3nvi and @nhakmiller have both asked for such a feature, and I spend ~30 minutes a day tearing down deployments. (I'm constantly tearing down and redeploying)
> 
> Plus, it guarantees that a user can completely remove a Panther deployment. There are artifacts right now that are left behind even if the CloudFormation stacks are deleted (ACM certificates, log groups)

Ι'm fully in for that. It also allows a company to "test us" and "remove us" if it thinks that we don't suit their problem.

Being able to install and uninstall I think is a core feature. It also allows us to:

1. Quickly test an E2E deployment before each release (and quickly tear it down afterwards)
2. Add a Panther deployment as part of certain PRs (where the project will be built with the code from the PR and then the project will be taken down when the PR is merged)
3. Do fresh deployments when breaking changes occur in pre-release version, where a new deployment is needed.

In general I personally think that the value of it is big and would be a requirement for v1 release
