### ISSUE TITLE
Design: Sensitive Fields in Destination

### ISSUE THREAD

**Issue by 3nvi** [panther-labs/panther#1356]
### Description

Currently, when a user is trying  to edit a field that is sensitive, we don't show the value of the field in the related form. This might confuse the user to think that the field is blank, although it's not.

### Acceptance Criteria

- Protect sensitive information of fields, while helping the user understand that they have hidden values
- Let the user understand that by filling in the blank field, the value will update

**Comment by dimitriszoitas** [comment]
The changes are [here](https://share.goabstract.com/b81ec1c6-38df-4861-9514-44cdea387aa9)

First of all I think that we should never leave a field blank. If we can't store the information or for whatever reason we can't "hide it" in a password-like way (with text bullets) then let's just have it dummy-filled. I'm suggesting a new field type (basically different border color, and an "alert" icon that when hovered a tooltip displays the text we want). 

While designing the edit page though, I realised that we've (I've) done a major -in my opinion- UX mistake. When editing, you dont really know what type of destination you're editing, and you'll have to go back and look again and edit again. Since we already have an icon-logic in sources onboarding I also suggest adding the icon of the destination type in both onboarding and editing. 

Also the edit flow should be consistent with the edit flows of the rules etc (with the buttons on top right), and apart from the save button we need to have a cancel button as well.

All these changes are open for discussion

**Comment by 3nvi** [comment]
> When editing, you dont really know what type of destination you're editing

You can literally see it above you in the title "Edit Jira Destination".

For the  rest I've left my comments on Abstract 😄

**Comment by dimitriszoitas** [comment]
In the creation of the destination - yes you can. In the edit of the destination you cannot. Either way for consistency (since we have this layout in sources for a whilte) adding an icon in a later version wont hurt, but for now we have to add the type of the destination somehow in the edit page.
