### ISSUE TITLE
Automatically lookup destinations in bulk upload

### ISSUE THREAD

**Issue by nhakmiller** [panther-labs/panther#1424]
### Describe the ideal solution

The new destination override feature allows rules to specify a specific destination to send alerts to, as opposed to the default destinations of that rule's severity. When specifying this destination override, the backend stores the unique ID of the destination which is not visible to users. This means that this field is virtually impossible to manage from the CLI.

The `BulkUpload` endpoint of the analysis API should automatically translate any "friendly name"s of destinations into the corresponding unique destination ID before writing the policies & rules to the backend.

### Describe your use cases

Managing policies & rules from the CLI using the panther_analysis_tool.

### How frequently would you use such feature

Every single time I upload policies & rules from the CLI, probably about once every other week.

### Describe alternatives you have considered

One alternative would be to have the CLI lookup this information and do the mapping itself. Another would be to have the unique ID of each destination visible in the UI, and then users could copy it into their rule specification files.

**Comment by TravisGary** [comment]
This would be a big help for us too.  We have only some alerts we want to send to pagerduty and those overrides get overwritten when we update from our CD process.

**Comment by wey-chiang** [comment]
Issue cloned.

**Comment by wey-chiang** [comment]
The implementation is included in #2699 

Note: rather than overwriting the destination names, we simply allow users to use the display name of the destination. This removes the need to overwrite any python code making it much easier to maintain.

Furthermore, the aforementioned implementation will also provide users refined feedback for invalid destinations returned by `destinations`. That is to say that all invalid/duplicate destinations returned by `destinations` will be shown in a `ValueError` error response in the unit test.
