### ISSUE TITLE
Enhance Sensitive Fields UI in Destinations

### ISSUE THREAD

**Issue by 3nvi** [panther-labs/panther#1442]
### Description

Currently, when a user is trying to update a field whose information is sensitive, the UI:

- Adds a `type="password"` to the underlying input to avoid over-the-shoulder attacks
- Doesn't display its previous value (since we don't want to sent it as part of a network request from the API)

This means that users consider the field "empty" when  they are trying to edit it. Funnily  enough, we have a  placeholder  notifying them that the input is actually hidden and **not** empty, but this placeholder only gets shown when the field actually gets focused.

All that prompted us to rethink the way we are doing this and ended up with the following design:

https://app.abstract.com/projects/558a8de6-7134-4c8b-91c5-62074bb1279b/branches/6c4082e9-dc0b-4e26-b60e-cc96e60306ee/commits/fc0e3669ae46aad9ff03e270ad13f07d58e1b9b9/files/8cc3cb34-8b80-405f-97ad-3adafc365a4f/layers/2795B634-BEA5-4AFF-A5C1-757F29AF007B

### Acceptance Criteria

- When editing  a sensitive field, the initial value for this field should be `*******************` . This should be saved in our constants file
- When editing  a sensitive field, show an info icon within the sensitive inputs of any destination form (as seen in the mocks)
- When editing  a sensitive field, hovering the info icon should show a tooltip explaining that the info is hidden for their protection (as seen in the mocks). The tooltip may wrap the entire input if needed, but should only be displayed when the value of the field is  `*******************`
- When updating a destination with a sensitive field, the API should replace the value of any fields with  the value of `*******************`, converting it to an empty  string (i.e. `''`). This way the API will know that this sensitive field was **not**
 updated by the user and it should retain its original value. This should ideally be done using a custom apollo link.

**Comment by 3nvi** [comment]
@nhakmiller and @s0l0ist  instead oof doing this manual transformation in the FE, would you be ok to send this fixed value from the API? This way if the user doesn't update the sensitive info, I'll just send back the same fixed value. In any other case, you can assume that the user will have manually overridden the value.

**Comment by s0l0ist** [comment]
@3nvi personally, I don't like passing strings to the backend as it increases the complexity of our input sanitization. Eventually, this  _could_ extend to more than 1 backend API whereas the frontend would only need to generate this component once and reuse.

I vote for the FE changes to make this happen. @nhakmiller?

**Comment by nhakmiller** [comment]
That is how this was previously implemented, more or less. The backend would send back `********` instead of a value, then the frontend would convert `********` to `nil` before sending it back (exactly for the input sanitation reasons that @s0l0ist mentioned). I would be ok with moving back to that.

Sending back `********` messes with the backend input validation, which is fairly rigid. We'd either have to throw out backend input validation for this API or entirely re-work it which would be a lot of effort. So process is:

- User clicks update destination button
- Frontend requests destination configuration from backend
- Backend constructs & sends response, replacing sensitive fields with `********`
- User changes some fields, hits update
- Frontend replaces any instances of `********` with `nil` (or empty string, I forget whether it's a pointer. Whatever we have now), and sends update request to backend

Would that be ok?

**Comment by 3nvi** [comment]
Hmm I'd prefer an all or nothing solution. Given the fact  that we  can achieve the same outcome without requiring any work on the BE layer. I vote for making the necessary (proposed) changes only on the FE layer to allow for quicker iterations.

Thanks a lot for your input
