### ISSUE TITLE
Align General Settings UI  with redesign needs

### ISSUE THREAD

**Issue by 3nvi** [panther-labs/panther#1462]
## Summary

We should make sure to align our designs to the General Settings page as shown in the mock ups

### Designs

https://app.abstract.com/projects/558a8de6-7134-4c8b-91c5-62074bb1279b/branches/39dcb3e2-1e72-49b2-afab-3a59c8459f66/commits/fc0e3669ae46aad9ff03e270ad13f07d58e1b9b9/files/8cc3cb34-8b80-405f-97ad-3adafc365a4f/layers/5A875BE7-2743-49D5-AB60-BCC80722F71D

### Acceptance Criteria

- Make sure that the UI fully aligns with designs
- Validate that all the functionality is present

**Comment by vorillaz** [comment]
Hey @dimitriszoitas , it seems that there is a mockup missing for Panther OS.
More precisely the OS version has a single column and a CTA targeting the marketing pricing page.
Can you please have a look ?

**Comment by 3nvi** [comment]
@dimitriszoitas ping

**Comment by dimitriszoitas** [comment]
@3nvi I have already fixed and closed this in [another issue](https://github.com/panther-labs/panther/issues/1626) since this is not a "design" issue, I had mentioned @vorillaz and I think we've already discussed that in a standup.

I'm going to change it again though to include the snowflake settings
