### ISSUE TITLE
Cloud Security doesn't find newly created S3 bucket

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther#1482]
### Describe the bug

New resource doesn't appear in Cloud Security view and the reason is that if users don't add S3 notifications, we don't showcase the s3 bucket at all under the resources tab.

### Steps to reproduce

1. Go to Cloud Security -> Sources
2. Add a new account. Make sure to check the Real-time events
3. Go to your account. Create a new S3 bucket.
4. Search for the bucket, it doesn't appear

### Expected behavior

I expected to be able to find the S3 bucket once I created it. I waited for 10' minutes, but nothing came through. 

### Designs

https://app.abstract.com/projects/558a8de6-7134-4c8b-91c5-62074bb1279b/branches/70fbde80-1195-4df9-a583-6962f57e3e19/commits/37590523135a8bd8a3e8a0ae7f6d46c8bb52b7ee/files/c2bbc1a8-4778-4cd6-93a5-4630d8868201/layers/470D23BE-968A-466D-8F4F-12EF02FCB18E

### Acceptance Criteria

- After the user has setup IAM we do a health check (as it already happens). If the user fails it, we should show an error screen. If the user passes the check (which happens while you see the hourglass), then the user should see a different screen (instead of showing a success screen as it happens now).
- Add another screeen in the wizard right after verification with the designs shown in the link above
- This step should only be present when:
  -  onboarding an S3 source if `enable real-time` checkbox is checked
  - when editing it if the user has gone fro "disabled" real-time to enabled

Contrary to the designs:
- The "read more" should link to `CLOUD_SECURITY_REAL_TIME_DOC_URL` and you should remove any other place where this link is referenced **within the same wizard**
- The title should change to "Enable Real-Time monitoring"
- The subtitle should change to "You can now follow the steps found here to enable support for real-time monitoring of your Panther account"
- The helper text should change to "Panther does not validate if your account has been configured for real-time cloud security analysis. Failing to do this, will not allow Panther to instantly notify you when something goes wrong"
- When the user clicks the "I have setup ...." you should direct him to a success page (there's no API request or response involved)

**Comment by nhakmiller** [comment]
Did you also complete the steps outline [here](https://docs.runpanther.io/v/v1.7-docs/cloud-security/setup#configure-real-time-monitoring) to deploy a stackset to enable real time monitoring? It appears the wizard no longer links to these steps (it links to some other docs instead), so at the very least we should update that.

**Comment by kostaspap** [comment]
> Did you also complete the steps outlined [here](https://docs.runpanther.io/v/v1.7-docs/cloud-security/setup#configure-real-time-monitoring) to deploy a stackset to enable real time monitoring? It appears the wizard no longer links to these steps (it links to some other docs instead), so at the very least we should update that.

No I did not - I actually didn't see any relevant links and though the behavior have have changed somehow. Yeah, we should update the links or wording for sure.

**Comment by kostaspap** [comment]
> > Did you also complete the steps outlined [here](https://docs.runpanther.io/v/v1.7-docs/cloud-security/setup#configure-real-time-monitoring) to deploy a stackset to enable real time monitoring? It appears the wizard no longer links to these steps (it links to some other docs instead), so at the very least we should update that.
> 
> No I did not - I actually didn't see any relevant links and though the behavior have have changed somehow. Yeah, we should update the links or wording for sure.

Shouldn't the health check fail if the real time monitoring is not enabled? Or is it one of those cases where we don't have permissions to check this?

**Comment by nhakmiller** [comment]
> No I did not - I actually didn't see any relevant links and though the behavior have have changed somehow. Yeah, we should update the links or wording for sure.

Yeah we used to link to it similar to how the SNS notification setup is required in log analysis. But it appears the wizard has been changed and now it links to a different place and calls it "read more".

> Shouldn't the health check fail if the real time monitoring is not enabled? Or is it one of those cases where we don't have permissions to check this?

The health check for real time monitoring is just checking that the `CWEStacksetExecution` role (or however it is called) is deployed and assumable by Panther. Which is:

1. Not really checking that real time is enabled, just that someone has the infra in place to setup real time monitoring if they wanted to
2. Not even a good assumption that the master account that should be managing these stack sets is Panther, although I suppose you can just not check the box and deploy the stackset execution role separately if that is a concern.

So not a great health check, but it's what we have currently.

> For many releases that's where it was. I was not aware we needed to deploy something additional to enable real-time monitoring, as I thought that the autogenerated cloudformation template already included that. Let me know if we need to update something

The "read more" link should point here: https://docs.runpanther.io/v/v1.7-docs/cloud-security/setup#configure-real-time-monitoring. I suspect actually that the wizard didn't change, but that the docs got changed in the re-orgs which broke some links and then the links got updated to this place afterwards. Also, we should re-word it to be something like "Additional steps required for real time scanning" or something like this, since the steps are required but only if you want to do the real time scanning setup.

**Comment by 3nvi** [comment]
> Also, we should re-word it to be something like "Additional steps required for real time scanning" or something like this, since the steps are required but only if you want to do the real time scanning setup.

@nhakmiller Should this be part  of 1.8? We need to go through @dimitriszoitas for it (we already have a similar task - as you pointed out - regarding Setting up S3 notifications). I can create an issue to track this, just want to know the urgency of it.

Also is there a way for the user to avoid this step? Is it something that a CFN template can handle down the line or is it a complex process that has to include manual steps?

**Comment by nhakmiller** [comment]
> @nhakmiller Should this be part of 1.8? We need to go through @dimitriszoitas for it (we already have a similar task - as you pointed out - regarding Setting up S3 notifications). I can create an issue to track this, just want to know the urgency of it.
> 
> Also is there a way for the user to avoid this step? Is it something that a CFN template can handle down the line or is it a complex process that has to include manual steps?

I think leaving for 1.9 is fine, the feature works the documentation/guidance is just confusing.

The manual steps are required not because the task is complex, but because of security considerations. We don't grant ourselves permissions to take certain actions, instead we setup the infrastructure for the user so that they can take those actions (but Panther cannot). This is because the permissions needed here are extremely powerful, in fact several users have identified this role as "having too much permissions" even though Panther cannot even use it.

For users who do not have these security concerns, it would be pretty easy to remove this manual step. But then they are granting the Panther application the permissions to create essentially any arbitrary resource in their accounts. I suppose we could explore an "easy mode" vs. "hard mode" setup, where in easy mode you grant panther these permissions and in hard mode you have to go do it yourself. But then there is a lot of UX considerations around that as well I'm sure.

**Comment by 3nvi** [comment]
@nhakmiller have we verified it's just a matter of  a missing step? Should I re-assign it to the web team?

**Comment by austinbyers** [comment]
Is this still planned for v1.9.0?

**Comment by alexmylonas** [comment]
I have stumbled into a behaviour that might be relevant to this.
Issue:
1. I have enabled auto-remediation(`AWS.S3.EnableBucketEncryption`) for the `AWS.S3.Bucket.Encryption` policy.
2. I created a bucket without encryption
3. Re-onboarded the cloudsec source to trigger a scan.
4. The bucket was auto-remediated successfully but the policy remained failing for this resource.

My best guess was that it was detected as failing, remediated but not updated (at least until the next scan)

**Comment by wey-chiang** [comment]
I'm wondering if this should be assigned to the web team.
I am unable to recreate this issue

Note that when testing, I did not add a new account (I used the existing `panther-account` used for deployment)
I created a new S3 bucket and it showed up pretty quickly
Is adding a new source a necessary step in reproducing this issue?

**Comment by s0l0ist** [comment]
@kostaspap , is this still an issue? I'll punt to v1.12 for now.

**Comment by 3nvi** [comment]
Re-assigning to web team. I feel there's gains we can get by adding an additional screen to remind the reader to setup his/hre notifications

**Comment by kostaspap** [comment]
> I'm wondering if this should be assigned to the web team.
> I am unable to recreate this issue
> 
> Note that when testing, I did not add a new account (I used the existing `panther-account` used for deployment)
> I created a new S3 bucket and it showed up pretty quickly
> Is adding a new source a necessary step in reproducing this issue?

@wey-chiang the issue is specific to the use case described by the "Steps to reproduce". The other usecase you described works indeed.
