### ISSUE TITLE
Total policies number hard to read

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther#1609]
### Describe the bug

The number of "Total policies" in the "Enabled Poliicies" section of the Dashboard are hard to read. The number is dark color that blends in the background.  

### Steps to reproduce

1. Go to Cloud Security dashboard

### Expected behavior

I would expect the number to be easily readable. 

### Environment

How are you deploying or using Panther?

- Panther version or commit: v1.9.0-RC1

### Screenshots

![Screen Shot 2020-09-25 at 9.46.53 AM.png](https://images.zenhubusercontent.com/5e4fc81c2009ef65e12fafd8/55e1167a-0e5e-4e25-a631-13e40eb2efe2)

**Comment by dimitriszoitas** [comment]
In the designs I've made we currently have: 

- Policies overview (passing and failing policies)
- Resources Health (Healthy and Unhleathy Resources)

I don't have a enabled policies somewhere that's why you didn't have the correct color

Please use the following colors:

- Total Policies: #0081C5
- Total Failing Policies: #E85959
- Total Resources: #14B597
- Total Enabled Policies: #7268A6

**Comment by 3nvi** [comment]
I didn't comment on this since it might be fixed after the page's designs  are finished
