### ISSUE TITLE
Empty Alerts Page Looks Bad

### ISSUE THREAD

**Issue by rleighton** [panther-labs/panther#1677]
### Describe the bug

The "status"  box in the alerts display does  not fix in the allocated space.

### Steps to reproduce

Open alerts page.

### Environment

This is oss `master`

### Screenshots

![image](https://user-images.githubusercontent.com/18419762/95256863-681a5100-07f1-11eb-9de5-8a0d336e6952.png)

**Comment by jacknagz** [comment]
@rleighton can you please use the `bug` template?

**Comment by 3nvi** [comment]
Thanks for reporting it.

We are aware of that and it's part of an internal transitional phase. It was created by a clash between our original designs and our business needs. We've already notified design and plan to have it mended before releasing.

Since there's no additional actionable item here, I'll be closing this ticket. 

P.S. I'll make sure to link it to the FE mending effort as soon as the designs are implemented
