### ISSUE TITLE
Access `udm` method in Rules Engine

### ISSUE THREAD

**Issue by lindsey-w** [panther-labs/panther#1812]
### Description

Support field mappings / user defined schema in rules engine. 

### Related Services
WIP
- This issue is strictly for the object instantiation / `udm` aspect of enabling field standardization  
- There is a related issue to upload logtype schemas

### Designs
WIP

### Acceptance Criteria
 
- Users can use `udm()` method in rules logic to access fields by standard name

**Comment by kostaspap** [comment]
I though the the `udm()` would be a function that would be applied on the event , e.g. `udm(event, "source_ip")`. 

If we are going to instantiate an event out of the Dict, we have to make sure to make it in a performant manner. E.g. we should avoid making deep copies of the data since this would double the memory allocations in a very performance sensitive system.

**Comment by lindsey-w** [comment]
My understanding was we wanted to call `udm` in the same way we can call `get` (so `event.udm('field')` and `event.get('field')` ) 

Considering your points, I think the exact implementation of it could go either way.
