### ISSUE TITLE
Snyk Setup

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther#1815]
### Description

Snyk is a DevSecOps platform that identifies security issues in application dependencies, containers, and infra-as-code. Today, we use a combination of various tools to scan application code (CodeQL) and dependencies (bandit, gosec, and npm-audit), but do not have a tool for container scanning of our web application.

This epic is to track our setup and configuration of Snyk.

### RFC

N/A

### Designs

N/A

### Acceptance Criteria

- Snyk can build and scan our frontend Docker image in CI ([example](https://github.com/snyk/actions/tree/master/docker))
- Snyk can scan our Terraform files for vulnerabilities in CI ([example](https://github.com/snyk/actions/tree/master/iac))
- Snyk can scan our OSS licenses in CI ([might be this?](https://github.com/snyk/actions/tree/master/setup))

**Comment by jacknagz** [comment]
Hey guys, just FYI we can't adjust the milestone again on this one

**Comment by austinbyers** [comment]
Yep, that's what we agreed as well

**Comment by austinbyers** [comment]
Additional context for @s0l0ist , who will be owning this task:

Snyk is currently managed here: https://app.snyk.io/org/jack.naglieri

## Docker Images
The `panther-buildpack` and `panther-development-pack` images for CI and development, respectively, are not in scope. These can be automatically scanned by ECR when we publish there (#2161 ), do not change very often, and are not shipped in Panther itself.

What needs to be scanned is the panther web image (`deployments/Dockerfile`), which, because of the npm install, might change on every commit. Snyk's last [example](https://github.com/snyk/actions/tree/master/docker) should work well - we just add a GitHub action which integrates with GitHub code scanning.

## Terraform
Panther itself has no Terraform; we only use it to provide an alternate form of the aux templates, which are very simple. Snyk's TF scanning is limited to one file at a time, which means we'd need to add a step for each TF file.

I'd say this should be best-effort - if it's easy to add the TF scanning, great, let's do it. If it poses difficulties, we can revisit this later.

## License scanning
It looks like this is already configured:

![Screen Shot 2020-11-30 at 4 11 50 PM](https://user-images.githubusercontent.com/3608925/100680635-cf9ed980-3326-11eb-8baf-b467ed57341c.png)

So maybe all we need to do here is remove the FOSSA config / badge
