### ISSUE TITLE
Filtering Alerts takes far too long on old alerts

### ISSUE THREAD

**Issue by 3nvi** [panther-labs/panther#1965]
### Description

Whenever I try and filter alerts by `nameContains`, the API response seems to be too slow. Other filters seem to come back relatively quick, but "title filtering" always takes more than 20 seconds.

While trying to identify the cause, I found out that:

- It only happens on the `nameContains` filtering
- I observed it on OSS where I have more alerts. Most of my alerts are also old.
- It happens on 1.12 release 

### Screenshots

<img width="1660" alt="Screen Shot 2020-11-06 at 12 27 13 PM" src="https://user-images.githubusercontent.com/10436045/98355930-801d0480-202b-11eb-9660-c16a167dacf2.png">

### Related Services

Alerts API

### Designs

N/A

### Reproduction Steps

1. Go to the List Alerts page
2. Open the Chrome Devtools on the Network tab
2. Use the title filtering and type a dummy string like "blahblahblah"
3. Wait and see how much time it takes for the UI to show the new set results (which should be empty)
4. See how much time the request took on the network tab

### Notes

My total alerts are 4,849

**Comment by kostaspap** [comment]
Filtering by name requires a full DDB scan. Depending on the number of alerts, this could take ... a while, especially if you provide a non existent title (we will scan through everything). 

Some ideas on how to improve the situation: 
1. Update the backend schema to allow faster lookups
2. Instead of waiting 20 seconds for a request to finish, maybe we could be sending to the FE smaller responses.

**Comment by 3nvi** [comment]
@s0l0ist I've tagged you as the owner, but feel free to remove yourself if need be

**Comment by kostaspap** [comment]
> Filtering by name requires a full DDB scan. Depending on the number of alerts, this could take ... a while, especially if you provide a non existent title (we will scan through everything).
> 
> Some ideas on how to improve the situation:
> 
> 1. Update the backend schema to allow faster lookups
> 2. Instead of waiting 20 seconds for a request to finish, maybe we could be sending to the FE smaller responses.

To elaborate on #1: We currently store ALL Alerts in the same DDB partition in order to allow for global time ordering. There are some problems with that: 
1. Any filtering operation that needs to happen in application level (e.g. title fuzzy matching) needs to happen inside the Lambda and it really hard to parallelize
2. DDB has a MAX partition size. This means we will eventually run out of disk space if we continue to store everything in the same partition. 

The way I have handled it in the past is using "rolling partition keys": Having "timestamp-based" partitions keys in DDB so that all the alerts of a single day/week/month will have the same primary key (the timestamp). That allows us: 
i) Avoid hitting the DDB partition size limitations
ii) Parallelize such filtering operations: We can issue few queries in parallel for different dates in the backend and process results faster.

**Comment by kostaspap** [comment]
I tried it in Aggelos installation and seeing the same slow responses. Some numbers: 
1. table has approx 4,849 alerts
2. DDB table size is approx 30MB
3. Lambda took 27 seconds to complete.

**Comment by 3nvi** [comment]
Thanks @kostaspap ! It's worth mentioning that at 30 seconds AppSync timeouts. Thus we are 3 seconds away from not receiving a response at all

**Comment by austinbyers** [comment]
* Short-term: addressed by #1967 
* Medium-term: we could add a `lowerName` column to filter on Dynamo's side (reduces number of Lambda-Dynamo calls)
* Long-term: We have to change the partition strategy, because all entries are currently in the same partition and there is a limit to its max size. We could also explore different DB backends, but that level of change is outside the scope of this

---

Leaving open (as P2) to add at least the pre-filter in Dynamo itself, which we have already in other APIs. Relatively easy change (requires a small migration to update existing entries)
