### ISSUE TITLE
During initial deployment, invite email sent before webservice is available

### ISSUE THREAD

**Issue by stoggi** [panther-labs/panther#197]
### Describe the bug

During an initial deployment with `mage deploy`, after receiving the invite email clicking on the Dashboard link in the email will lead to a 503 error. The web service is deployed after setting up the Panther admin user, and took about 3-4 minutes before the page could be loaded.

### Steps to reproduce

1. Deploy a new Panther environment
2. Click on the `Dashboard` url in the admin user invite email
3. Observe a 503 error
4. Wait 3-4 minutes until the web service has been deployed
5. Reload dashboard and get presented with sign in page

### Expected behavior

While this is a very minor, people may think their deploy hasn't worked. It's not clear the web service had not yet been deployed or a delay is to be expected.

The email text could mention to wait until the deployment is complete, or delay sending the invite email until the web service has been deployed.

### Environment

How are you deploying or using Panther?

- Panther master at commit 48f2f244d453bb0cbaa3077c7d80f024b1a97a5c
- OS: Linux (Manjaro 19)
- Deployment method: docker container via ./dev.sh

**Comment by 3nvi** [comment]
It takes some time for ECS to reach consistency. We can definitely use the aws sdk to get this information and send the email after this check is made.

The reason though that you see it is because the invitation gets sent before the UI is created (for some reason).

I can easily revert the order and add a check to make sure that the email is sent after the related ECS service is stable, but @austinbyers might be making some changes in #213, so perhaps we can include it there?

**Comment by austinbyers** [comment]
This is just because we setup the first user after the main backend stack, before the web has even been deployed.

The fix would be to just move the `postDeploySetup` after all stacks have deployed, which makes more sense anyway

**Comment by austinbyers** [comment]
I'll put this in a separate PR, #213 is too big and is ready to merge
