### ISSUE TITLE
Most active rules does not appear to work

### ISSUE THREAD

**Issue by mattthetraveler** [panther-labs/panther#2059]
### Describe the bug

When you switch to most active rules tab in Log Analysis Overview, the view shows the least active rules (rules with least amount of alerts)

### Steps to reproduce

1. Go to Overview in Log Analysis
2. Toggle over to Most Active Rules in top visualization
3. See results like below

### Expected behavior

Should show rules with the most alerts

### Environment

- Panther version or commit: v1.12.1-release-1.13-01aa240ce

### Screenshots

![image.png](https://images.zenhubusercontent.com/5f99c6c3032b975d7ec7e099/f9ab5c23-75a4-4f1d-917f-5d110fad4926)

**Comment by mattthetraveler** [comment]
FYI @3nvi found this in our dogfooding session yesterday, would your team own this?

**Comment by 3nvi** [comment]
Not sure. Will have to investigate to see if it's a FE or BE issue.

**Comment by 3nvi** [comment]
I've:

1. checked the related code and validated that it hasn't changed since 1.12 release
2. Verified that the API returns an empty list for the `alertsByRuleID` (see 1st SS)
3. Validated that this is not an appsync error, but this is indeed the response that comes from the lambda (see 2nd SS)


For these reasons, I'm **assuming** it's related to the security team, so I'm including them in to see where the issue exists. @nhakmiller  thoughts?

<img width="904" alt="Screen Shot 2020-11-19 at 11 30 24 AM" src="https://user-images.githubusercontent.com/10436045/99655709-b82d3a00-2a64-11eb-8243-7c24346e3940.png">
<img width="1380" alt="Screen Shot 2020-11-19 at 12 39 32 PM" src="https://user-images.githubusercontent.com/10436045/99655726-ba8f9400-2a64-11eb-9585-93a118b93168.png">

**Comment by nhakmiller** [comment]
> For these reasons, I'm **assuming** it's related to the security team, so I'm including them in to see where the issue exists. @nhakmiller thoughts?

Could be, we can take a look.

**Comment by 3nvi** [comment]
@nhakmiller any updates?

**Comment by nhakmiller** [comment]
> @nhakmiller any updates?

No.

**Comment by s0l0ist** [comment]
Punted to v1.14, but we do need a fix for this.

**Comment by s0l0ist** [comment]
related to #2178

**Comment by 3nvi** [comment]
@lindsey-w I think the reason this happens is that the deployment simply doesn't have any data. If you don't find an anomaly, feel free to close this in favor of #2178
