### ISSUE TITLE
Query 'getIntegrationTemplate' fails with AccessDenied

### ISSUE THREAD

**Issue by alexmylonas** [panther-labs/panther#2149]
### Describe the bug

There is an issue when trying to onboard a new S3 log source. 

The issue is apparent when getting to the Setup IAM roles in UI
**The query for getting the CFN template fails with:**
```
[
  {
    "path": [
      "getS3LogIntegrationTemplate"
    ],
    "data": null,
    "errorType": "Lambda:Unhandled",
    "errorInfo": null,
    "locations": [
      {
        "line": 2,
        "column": 3,
        "sourceName": null
      }
    ],
    "message": "AccessDenied: Access Denied\n\tstatus code: 403, request id: C0B7A4B79207E8FD, host id: pX2nfVvi4+g4a4Cc/GOim4mm+N9eYZQz+Hf1CW8xW4o0ogLsH7chP5+lYck2dxUpsuSnr+hioyc="
  }
]
```
### Steps to reproduce

1. Go to `ListLogSource`
2. Click on New Source
3. Add inputs on first screen
4. Click Continue
5. You 'll get a failing pop up for this query

### Expected behavior

Query should be executed properly

### Environment

- Panther version or commit: de762b5b718e8952df8dc6cea4b9ed94fbe5ca3a

### Notes

A possible root cause could be related to this [PR](https://github.com/panther-labs/panther/pull/2077/files)

**Comment by austinbyers** [comment]
Closing as a duplicate of https://github.com/panther-labs/panther-enterprise/issues/1594. I verified this has been fixed in the release environment.

The problem is just that we need to publish the auxiliary templates with `v1.14.0` instead of `v1.14.0-RC`. Since the problem can be fixed by just publishing templates, it's not really a problem with the app itself, and I'm closing the issue.

However, I'm going to take #2158 and work on passing consistent version information everywhere to prevent this from happening again in the future
