### ISSUE TITLE
Design for Unit Test Mocking in Detections

### ISSUE THREAD

**Issue by mattthetraveler** [panther-labs/panther#2254]
### Description

As an analyst, I want to "replicate" an external api call against a rule/policy to test out the the logic before I actually activate the rule/policy.

Currently, the UI does not support mocking of external api calls. This prevents users from unit testing any logic that relies on these api calls. Adding support for mocking will allow us to more fully support unit testing in generic rule/policy logic.

### RFC

[PR for RFC](https://github.com/panther-labs/panther-enterprise/pull/967/files)

### Designs

TBD

### Acceptance Criteria

- In the test record section of the "edit" policy/rule pages, add ability to "add Mock" to an individual test record
  - when this is selected, the user should be able to select from existing mocks or add a new mock (perhaps in a pop up screen or a dropdown)
  - When user adds a new mock, they should be able to define the following fields and then hit "Apply":
    - mock function name (in Python)
    - desired return value (in Python)

**Comment by dimitriszoitas** [comment]
Hey @mattthetraveler I will need a bit more explanation for this issue because it's unclear to me what I have to do, and what the user flow exactly is

**Comment by mattthetraveler** [comment]
hi @dimitriszoitas I've updated the criteria with more details, let me know if this helps. @wey-chiang and @lindsey-w let me know if I've described the UI accurately here

**Comment by mattthetraveler** [comment]
Hi @wey-chiang and @lindsey-w checking in again here, want to make sure designs are queued up for the web team in Q1. Anything missing in the acceptance criteria?

**Comment by jacknagz** [comment]
@dimitriszoitas please update this with the design link, thanks!

**Comment by wey-chiang** [comment]
The acceptance criteria LGTM

Just to reiterate the point: each set of mocks should correspond to the individual test record and not the rule itself.

**Comment by dimitriszoitas** [comment]
Hey @mattthetraveler @wey-chiang @vorillaz @alexmylonas 

I've added the mockups related to this issue in [this miro board](https://miro.com/app/board/o9J_lTlm7KM=/)

A few questions that emerged while I was working on this:

1. Do we add multiple mocks in a test? or just one?
2. Every time we create a new mock, do we also save it so that we can use it at a later time? This is my current approach fyi
3. When creating a new mock, do we need a separate field to have the mock function name? Since it's in python I guess we could just use one editor for the whole function.
4. After we select the mock, is it embedded in the test function or should I just display somehow that the xxx test.mock is selected? (The latter is my current approach)
5. Should we be expecting some kind of response specific to the mock in the results after we run the test? And if so, what should it be?
6. I've used a sample mock in python after I googled it. Please give me a proper test-mock so we can have realistic data related to: 1. the rule 2. the test

Thank you

**Comment by mattthetraveler** [comment]
> 1. Do we add multiple mocks in a test? or just one?

This may depend on what's supportable by the work that @wey-chiang did. It would be cool to do multiple.

> 2. Every time we create a new mock, do we also save it so that we can use it at a later time? This is my current approach fyi

This would also be very cool, but depends on whether or not the API will support this. This could end up being an MMP feature. I'll defer to @wey-chiang as well

> 3. When creating a new mock, do we need a separate field to have the mock function name? Since it's in python I guess we could just use one editor for the whole function.

Yes I think we should have a separate field for name.

> 4. After we select the mock, is it embedded in the test function or should I just display somehow that the xxx test.mock is selected? (The latter is my current approach)

The latter is more clear to the user, I would prefer that

> 5. Should we be expecting some kind of response specific to the mock in the results after we run the test? And if so, what should it be?

I think this should be a requirement. The user should be able to see a sample alert (if one is returned) or some sort of response that indicates how detection is functioning. Open to thought on this.

> 6. I've used a sample mock in python after I googled it. Please give me a proper test-mock so we can have realistic data related to: 1. the rule 2. the test

I'll defer to @wey-chiang on this

**Comment by vorillaz** [comment]
@dimitriszoitas Just a minor note regarding the modal raising the mocking function, essentially I think we shall provide a blank slate when no mocks are in place.

@wey-chiang @mattthetraveler I am not quite sure, and I couldn't safely say from the RFC if the mocks are reusable. Like, are mocks globally available through an API listing? Are they provided in an automatic way where we are detecting external API calls and when they are applicable we can mock the call without any further implementation details?

In my perspective, I would expect something more holistic, and as far as I can tell I would expect a user based scenario where:

1. A user creates or edits a rule where `my_function()` and `my_function_1()`are used in Python 
2. For a test assertion `my_fuction` and  `my_function_1()` can get mocked with some returning values.

I don't think there should be any additional dropdowns or modals involved, just collapsable dynamic rows where the bodies of the functions could get declared.

**Comment by wey-chiang** [comment]
> Do we add multiple mocks in a test? or just one?

Multiple for a test. A set of mocks correspond to a test event which is to say that just because a function is mocked for one test event does not mean it will be mocked for another.

> Every time we create a new mock, do we also save it so that we can use it at a later time? This is my current approach fyi

Mocks are stored as part of the test `event`. So yes we save it, however if you wanted to reuse it, then you would have to parse the event data. That is to say: there is no direct api call that would just return a set of used mocks as the mocks would be packaged together with the test event data.

> When creating a new mock, do we need a separate field to have the mock function name? Since it's in python I guess we could just use one editor for the whole function.

For each mock there would be two fields: the function name to mock and the return value corresponding to that function mock.

> After we select the mock, is it embedded in the test function or should I just display somehow that the xxx test.mock is selected? (The latter is my current approach)

The latter -- the mock is not embedded in the test function rather, we run the test function inside a patched context.

> Should we be expecting some kind of response specific to the mock in the results after we run the test? And if so, what should it be?

No. 

> Please give me a proper test-mock so we can have realistic data related to: 1. the rule 2. the test

This is based on what I used to test the BE directly.

Packaged with the test event:

```
{
    ...
    "mocks": {
        "boto3": "boto3_return_value",
        "date": "date_return_value",
    }
    ...
}
```

The idea here is that a user would be able to specify the name of the function to mock (e.g. an external api call) and the value corresponding to that would be any object that the rest of the code is expecting to receive. If they were to make that external API call and get the response, assuming it's a valid python object, they would be able to paste in that response.

--

Based on what is up on Miro, those features (more complex python mocking support) would be a part of the MMP or MDP which we could implement with the stubbing framework proposed by @georgepsarakis
