### ISSUE TITLE
S3 Log Source Does not Display Set Prefix

### ISSUE THREAD

**Issue by rleighton** [panther-labs/panther#2323]
### Describe the bug

If you set a prefix for an S3 source it is not displayed in the summary, see screen shots.

![image](https://user-images.githubusercontent.com/18419762/102902642-49fddd80-443d-11eb-9841-044aeef765ca.png)

![image](https://user-images.githubusercontent.com/18419762/102902721-584bf980-443d-11eb-978d-dd20899813d5.png)

**Comment by 3nvi** [comment]
Because each log type is associated with a single S3 prefix, I think we should do one of the following:

- Remove the `S3 Prefix` entry altogether and allow users to see it when editing a source
- Show a list of `S3 Prefixes` that are used 
- Show groups of `S3 Prefix - Log Type` entries, but that would potentially require a new design by @dimitriszoitas 

@alexmylonas Have we already made a decision on this?

**Comment by alexmylonas** [comment]
We have decided with @giorgosp to remove the display of prefixes on the S3 Log Source card but seems the fields werent removed. 

I can create a small PR to fix that, if we are still ok with that.

What do you think @giorgosp?

**Comment by giorgosp** [comment]
At the very least we should remove the s3 prefix display since it will just be empty for new/updated sources.

**Comment by 3nvi** [comment]
Cool, let's remove it altogether and we'll re-instate if we need to. Allowing the users to see the log types is  more than enough for now, since they are rarely gonna be adding multiple S3 sources with the **same** logtypes but different prefixes.

@alexmylonas can you own it?
