### ISSUE TITLE
Support AWS Config logs

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther#2472]
### Description

Support AWS Config logs: https://docs.aws.amazon.com/config/latest/developerguide/WhatIsConfig.html

### Related Services

panther-log-processor

### Acceptance Criteria

- Panther supports AWS Config logs

**Comment by georgepsarakis** [comment]
## Introduction

AWS Config is responsible for recording the configuration changes of AWS resources, for example an EC2 instance type change. In addition, it can also perform a set of checks and characterize the resource as compliant or not, according to the  given set of policies.

> Note that not all resource types and resource IDs are supported, but may be included as references. For more information on supported resources, see [here](https://docs.aws.amazon.com/config/latest/developerguide/resource-config-reference.html).

## Compliance

### Rules

Rules can be either [Managed by AWS](https://docs.aws.amazon.com/config/latest/developerguide/evaluate-config_use-managed-rules.html) or created as [custom](https://docs.aws.amazon.com/config/latest/developerguide/evaluate-config_develop-rules.html) by the user. An example [Managed Rule](https://docs.aws.amazon.com/config/latest/developerguide/managed-rules-by-aws-config.html) is a check that an [ALB has always configured HTTP-to-HTTPS redirect](https://docs.aws.amazon.com/config/latest/developerguide/alb-http-to-https-redirection-check.html) listener rule.

## Outputs

AWS uses two delivery channels:
- [SNS Topic for notifications](https://docs.aws.amazon.com/config/latest/developerguide/notifications-for-AWS-Config.html) that are triggered exactly after a configuration / compliance change:
  - Configuration Item Change
  - Compliance Change
  - History Delivery Notification
  - Snapshot Delivery Notification
  - Oversized Configuration Item Change Notification (e.g. large Cloudformation stack changes).
- S3 Bucket for Resource Histories and Snapshots, as well as [Oversized Notifications](https://docs.aws.amazon.com/config/latest/developerguide/oversized-notification-example.html), which exceed the maximum SNS message size.

Notifications also contain the differences between the two configuration versions, perhaps allowing for easier change detection on specific attributes.

### Frequency

- Notifications (including oversized) are published to the SNS topic shortly after the configuration or compliance change.
- Rule Evaluation can be scheduled at regular intervals, ranging from 1 hour to 24 hours. Note however that rule evaluation happens for the resource when its configuration changes.
- For each recorded resource type, the [configuration history is sent to the S3 bucket **every six hours**](https://docs.aws.amazon.com/config/latest/developerguide/how-does-config-work.html#delivery-channel-S3-bucket).
- Snapshots can be delivered on demand, but they also seem to be automatically generated every hour.

## Sample Extraction Setup

In order to capture all SNS notifications, a [subscription to Firehose Delivery Stream](https://docs.aws.amazon.com/sns/latest/dg/firehose-example-subscribe-delivery-stream-to-topic.html) was created, which in its turn used an S3 bucket as a destination. A small Lambda function was required, in order to append newlines to each serialized notification, so that newline-delimited JSON files are stored in S3. This was mainly for inspection, but for Panther we can possibly use SNS-to-SQS fanout.

Snapshots and resource configuration histories are delivered on the S3 bucket in regular intervals and contain a single line with a JSON record.

## Log Structure

### Common Fields

| Field | Type | Description / Example |
| ---- | ---- | ---- |
| `ARN` | String | The resource ARN |
| `availabilityZone` | String | `"Not Applicable"`, `"Regional"`, `"us-west-2a"` |
| `awsAccountId` | String | The AWS Account ID |
| `awsRegion` | String | `"us-west-2"` |
| `configuration` | Object | Arbitrary structure, contains the name-value mapping of resource settings. Values are always JSON-encoded strings. |
| `configurationItemStatus` | String | `"OK"`, `"ResourceDiscovered"` (applies to [third-party resources](https://docs.aws.amazon.com/config/latest/developerguide/customresources-cli.html#view-custom-resource-type-cli) as well) |
| `configurationItemVersion` | String | `"1.3"` incremented version number |
| `configurationStateId` | Int64 | _UNKNOWN_ |
| `configurationStateMd5Hash` | String | Likely the state fingerprint. Empty for snapshots and history. |
| `relatedEvents` | Array | _UNKNOWN_ |
| `relationships`| `Array[Object]` | Connected resources |
| `relationships.[N].[name]` | String | Relation type in human-friendly form, as a label, e.g. `"Contains "` |
| `relationships.[N].[resourceName]` | String | The resource name, e.g. IAM Role name. |
| `relationships.[N].[resourceType]` | String | The resource type, e.g. `AWS::IAM::Role` |
| `resourceCreationTime` | String | The timestamp of the resource creation, e.g. `"2021-01-13T13:19:36.077Z"` |
| `resourceId` | String | The resource identifier composed by the resource type and the ARN `AWS::ElasticLoadBalancingV2::LoadBalancer/<ARN>` |
| `resourceName` | String | The human-friendly resource label |
| `resourceType` | String | The resource type, e.g. `AWS::Cloudwatch::Alarm` |
| supplementaryConfiguration | Object | See `configuration` |
| `tags` | Object | The assigned tag name-value pairs (can be [extracted by Panther](https://github.com/panther-labs/panther/blob/33b3b25615947f012ec048851e0154eb4e4b5688/internal/log_analysis/log_processor/parsers/awslogs/indicators.go#L44)) |

### Configuration Item Change Notification

Apart from the `Common Fields`, the following are also found in this notification type.

| Field | Type | Description/Example |
| ---- | ---- | ---- |
| `configurationItemDiff` | Object | - |
| `configurationItemDiff.[changedProperties]` | Object | - |
| `configurationItemDiff.[changedProperties].[Configuration.<SettingName>] | Object | - |
| `configurationItemDiff.[changedProperties].[Configuration.<SettingName>].[previousValue] | String | The previous setting value (likely JSON-encoded) |
| `configurationItemDiff.[changedProperties].[Configuration.<SettingName>].[updatedValue] | String | The new setting value (likely JSON-encoded) |
| `configurationItemDiff.[changedProperties].[Configuration.<SettingName>].[changeType] | String | Operation type: `CREATE`, `UPDATE`, `DELETE` |


### Compliance Change

| Field | Type | Description/Example |
| ---- | ---- | ---- |
| `awsAccountId` | String | The AWS Account ID |
| `awsRegion` | String | Example: `"us-west-2"` |
| `configRuleARN` | String | The [configuration rule](https://docs.aws.amazon.com/config/latest/developerguide/evaluate-config.html) ARN |
| `configRuleName` | String | The configuration rule name, e.g. `"alb-http-to-https-redirection-check"` |
| `messageType` | String | `ComplianceChangeNotification` |
| `newEvaluationResult` | Object | - |
| `newEvaluationResult.[evaluationResultIdentifier].[evaluationResultQualifier].[configRuleName] | String | See top-level field. |
| `newEvaluationResult.[evaluationResultIdentifier].[evaluationResultQualifier].[resourceType] | String | The evaluated resource's type, e.g. `"AWS::ElasticLoadBalancingV2::LoadBalancer"` |
| `newEvaluationResult.[evaluationResultIdentifier].[evaluationResultQualifier].[resourceId] | String | The evaluated resource's ID, e.g. `"AWS::ElasticLoadBalancingV2::LoadBalancer/<ARN>"` |
| `newEvaluationResult.[evaluationResultIdentifier].[orderingTimestamp] | String | Timestamp, possibly used for rule sorting. |
| `newEvaluationResult.[complianceType]` | String | Constant, one of `COMPLIANT`, `NON_COMPLIANT` |
| `newEvaluationResult.[resultRecordedTime]` | String | Possibly the timestamp of the evaluation recording. |
| `newEvaluationResult.[configRuleInvokedTime]` | String | Timestamp of the rule invocation. |
| `newEvaluationResult.[annotation]` | String | Hint, e.g. `HTTP listener must have HTTP to HTTPS redirection action configured` |
| `notificationCreationTime` | String | Timestamp |
| `oldEvaluationResult` | Object | Same structure as `oldEvaluationResult`. `null` for the first evaluation. `
| `recordVersion` | String | `"1.0"` |
| `resourceId` | String | The resource ARN (not prefixed by resource type |
| `resourceType` | String | The name of the resource type, e.g. `AWS::ElasticLoadBalancingV2::LoadBalancer` |


### Snapshots

> One file contains the configuration for all resources.

All resource configurations are included in an Array under the key `configurationItems`. The Common Fields are defined for each element. 

An additional containing the snapshot identifier is also a top-level field:

```
"configSnapshotId": "11111-2222-3333-4444",
"configurationsItems": [...]
```
### Resource History

> One file is generated per resource type.

All resource configurations are included in an Array under the key `configurationItems`. The Common Fields are defined for each element. 

#### Compliance

Compliance has its own resource type `AWS::Config::ResourceCompliance`.
A subset of `Common Fields`, with a structured `configuration` field value. 

| Field | Type | Description/Example |
| ---- | ---- | ---- |
| `complianceType` | String | See notification |
| `configRuleList` | Array[Object] | - |
| `configRuleList.[N].[complianceType] | String | See top-level field. |
| `configRuleList.[N].[configRuleArn] | String | See notifications. |
| `configRuleList.[N].[configRuleId] | String | Identifier, e.g. `config-rule-jf9s8k` |
| `configRuleList.[N].[configRuleName] | String | See notifications, e.g. `alb-http-to-https-redirection-check`. |
| `targetResourceId` | String | ARN of the resource that this rule applies to. |
| `targetResourcetype` | String | The resource type that this rule applies to. |
| `relationships` | Array[Object] | Related resources |
| `relationships.[name]` | String | The relationship label: `"Is Associated With "` |
| `relationships.[resourceId]` | String | Resource ARN |
| `relationships.[resourceType]` | String | For example: `AWS::ElasticLoadBalancingV2::LoadBalancer` |


### Preliminary Implementation Considerations

- It is likely that we need to handle both arrays and a single nested object, under two different keys. This was observed in a Configuration Item Change notification, where either `configurationItems: [...]` or `configurationItem: {...}` can be encountered. I think this already happens with CloudTrail logs, which usually contain a `Records` array.
- A single History or Snapshot dump corresponds to multiple log entries (one per resource).
- It may be beneficial to inject the snapshot ID as a tracing identifier for records originating from Snapshots. Not sure if these are actually consistent snapshots (I think we can safely assume that they aren't), but it may be useful to be able to differentiate History from Snapshot entries.
- Configuration Item Diff changeset entries have dynamic keys, `Configuration.<PropertyName>: {...}`, but the inner object structure seems consistent. The additional dot in the name could create some issues with tools / libraries that use this notation to detect nested objects. These entries could be rewritten as arrays, where the property name is added as an extra field.
- Deeply nested fields could possibly become top-level, for example `newEvaluationResult.[evaluationResultIdentifier].[evaluationResultQualifier].[configRuleName]`.

**Comment by kostaspap** [comment]
Thanks for the very detailed analysis! 

As discussed offline with @georgepsarakis we will just go for `Snapshots` and `Resource History` logs.
