### ISSUE TITLE
[BE] Salesforce log support MVP set

### ISSUE THREAD

**Issue by mattthetraveler** [panther-labs/panther#2529]
## Description

As an analyst, I want to be able to pull important Salesforce audit logs via a SaaS log experience.

## Acceptance Criteria

- Support for MVP set of Salesforce log types

**Comment by georgepsarakis** [comment]
## Introduction

Salesforce provides [Event Monitoring Data](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/using_resources_event_log_files.htm) in the form of CSV files, containing different fields per [Event Type](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_eventlogfile_supportedeventtypes.htm). Event Log files are available on an hourly and daily basis. Through the SOAP and REST APIs, a user with the appropriate permissions can request the manifest for these files, by providing a custom [SQL-dialect query](https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select.htm). After retrieving the file list, each file can be downloaded and parsed accordingly.

Salesforce makes available a [Developer Edition](https://developer.salesforce.com/signup) so that developers can test apps and integrations. I have created an account and I will proceed with sharing credentials and/or invite other team members.

## Authentication & Authorization

### Authentication

Users in Salesforce must have a unique username but not email necessarily. Thus an administrator can create an account for integration purposes, in order to grant read permissions to Panther.

Authenticating through the [REST API](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/quickstart_oauth.htm) requires:
- A [Connected App](https://help.salesforce.com/articleView?id=sf.connected_app_create.htm&type=5) to be created.
- After obtaining the Client ID & Secret, you can either follow the full OAuth2 flow (requires a webserver - even local), or use the App credentials along with the user credentials to obtain a Session ID, which is another type of authentication token.

The above seems quite complicated and we can possibly review the full OAuth2 flow at a later time.

The alternative would be to use the [SOAP API](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_calls_login.htm) to login and obtain the Session ID, which can then be used in REST requests.

Apart from the username and password, authenticating via the API requires also obtaining the [Security Token](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_concepts_security.htm#topic-title_login_token) for the account, which is a generated key by Salesforce. This key is concatenated to the password and used as an API credential. Note that there is also a permission named `Multi-Factor Authentication on API Logins` which will require TOTP token, but it is not entirely clear how this works. The Security Token is not automatically reset, but the user can reset it explicitly or by resetting the password.

In my prototype (Python), I have managed to successfully obtain a Session ID via the SOAP API and proceed with using the REST API endpoints for a sample integration user with the permissions mentioned in the next section. The authentication request happens on a central login endpoint, but subsequent API requests happen on the Instance URL. This information is retrieved in the authentication response, so it is not necessary to be provided as user input when configuring the source.

The required fields for authentication are:
- Username
- Password
- Security Token

### Authorization

The necessary permissions for the connecting API user account are:
- `System Permissions -> API Enabled`
- `System Permissions -> View Event Log Files`

References to the required permissions can also be found [here](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_eventlogfile.htm).

Access to event log data is read-only and they cannot be modified. As far as I have checked, this user does not have access to other resources (except for their own data), for example Reports created by a different user.

## Data Retrieval

### Event Types & Parsing

The most useful in the security context event types seem to be the following:
1. [Login](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_eventlogfile_login.htm)
2. [LoginAs](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_eventlogfile_loginas.htm)
3. [Logout](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_eventlogfile_logout.htm)
4. [URI](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_eventlogfile_uri.htm)
5. [InsecureExternalAssets](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_eventlogfile_insecureexternalassets.htm)

Each event type contains different information and fields but there are common fields that can be characterized as mandatory and distinguish this parser from others. Since the `EVENT_TYPE` field can be used to differentiate between events, we can use a single parser defining the superset of all event type fields and consequently a single Athena table. 

Note that it is likely that only event types (1), (3) and (5) are offered on all Salesforce plans by default. Quoting from the [documentation](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_eventlogfile_supportedeventtypes.htm):

> The Insecure External Assets, Login, and Logout events are available in supported Salesforce editions at no additional cost. Contact Salesforce to purchase the remaining event types.

### Obtaining the Event Log File manifest

We can query for Hourly event log files using the `query` endpoint, as mentioned [here](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/event_log_file_hourly_query.htm). Note that hourly files may take 3 to 6 hours to be available for download and data for the same hour may be split into multiple files. The recommendation is thus to check the file creation timestamp, since files can be added at a later time.

Since we need to define our query in SOQL, I concluded to the following:

```sql
Select Id, EventType, Sequence, Interval, LogDate, CreatedDate 
From EventLogFile WHERE (EventType = 'URI' OR EventType = 'Login' OR EventType = 'Logout' 
    OR EventType = 'LoginAs' OR EventType = 'InsecureExternalAssets') 
AND Interval = 'Hourly' AND CreatedDate >= 2020-02-03T12:00:00Z
ORDER BY CreatedDate ASC
```

<details>
<summary>Sample Manifest Entry</summary>

```json
{
    "attributes" : {
      "type" : "EventLogFile",
      "url" : "/services/data/v50.0/sobjects/EventLogFile/0AT4x00000aIEXAMPLE"
    },
    "Id" : "0AT4x00000aIEXAMPLE",
    "EventType" : "Login",
    "Sequence" : 1,
    "Interval" : "Hourly",
    "LogDate" : "2021-02-02T11:00:00.000+0000",
    "CreatedDate" : "2021-02-02T13:04:16.000+0000"
  }
```
</details>

The above will return the most recently created files first. As checkpoint data we need to retain the `CreatedDate` timestamp for the last record that we processed, along with the IDs of the files that we have already parsed during this run with this particular timestamp.

### Obtaining Event Log Files

The CSV file can be retrieved with with an authenticated REST API call `/services/data/v50.0/sobjects/EventLogFile/0AT4x00000aIEXAMPLE/LogFile`. No other parameters are required, but additional headers may apply for compression.

Note that each file contains records of a specific event type only. The following sample is for the `Login`, `LoginAs` and `URI` event types respectively.

<details>
<summary>LoginAs</summary>

```
"EVENT_TYPE","TIMESTAMP","REQUEST_ID","ORGANIZATION_ID","USER_ID","RUN_TIME","CPU_TIME","URI","SESSION_KEY","LOGIN_KEY","DELEGATED_USER_NAME","DELEGATED_USER_ID","TIMESTAMP_DERIVED","USER_ID_DERIVED","CLIENT_IP","URI_ID_DERIVED","DELEGATED_USER_ID_DERIVED"
"LoginAs","20210203123820.002","4a-x8Ufy4n374GkoqZhVM-","00D4x0000017wq6","0054x000004Btmm","68","15","/visualforce/session","wq/ADytreyV2GHaI","yYtfdrerMJtu34jH","<username>@runpanther.io","0054x000001L78a","2021-02-03T12:38:20.002Z","0054x000004BtmmAAC","10.0.0.1","","0054x000001L78aAAC"
```

</details>

<details>
<summary>Login</summary>

```
"EVENT_TYPE","TIMESTAMP","REQUEST_ID","ORGANIZATION_ID","USER_ID","RUN_TIME","CPU_TIME","URI","SESSION_KEY","LOGIN_KEY","REQUEST_STATUS","DB_TOTAL_TIME","BROWSER_TYPE","API_TYPE","API_VERSION","USER_NAME","TLS_PROTOCOL","CIPHER_SUITE","TIMESTAMP_DERIVED","USER_ID_DERIVED","CLIENT_IP","URI_ID_DERIVED","LOGIN_STATUS","SOURCE_IP"
"Login","20210203123641.767","4a-x2l_OMgKK3AWOblLdo-","00D4x0000017wq6","0054x000001L78a","96","54","/index.jsp","","yYtfdrerMJtu34jH","","38724581","Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv%3A85.0) Gecko/20100101 Firefox/85.0","","9998.0","<username>@runpanther.io","TLSv1.2","ECDHE-RSA-AES256-GCM-SHA384","2021-02-03T12:36:41.767Z","0054x000001L78aAAC","10.0.0.1","","LOGIN_NO_ERROR","10.0.0.1"
```

</details>

<details>
<summary>URI</summary>

```
"EVENT_TYPE","TIMESTAMP","REQUEST_ID","ORGANIZATION_ID","USER_ID","RUN_TIME","CPU_TIME","URI","SESSION_KEY","LOGIN_KEY","REQUEST_STATUS","DB_TOTAL_TIME","DB_BLOCKS","DB_CPU_TIME","REFERRER_URI","TIMESTAMP_DERIVED","USER_ID_DERIVED","CLIENT_IP","URI_ID_DERIVED"
"URI","20210203154432.925","4a06Iq-nlyRUqAWOblLeB-","00D4x0000017wq6","0054x000004Btmm","69","25","/secur/frontdoor.jsp","bZMqhGMPH7kHQnwu","7D/vGFUiSTiP88D/","R","26936118","94","0","","2021-02-03T15:44:32.925Z","0054x000004BtmmAAC","10.0.0.1",""
```

</details>

The URI files are likely to be the larger ones that we might encounter but are a form of Audit Logs so they seem quite important.

## Operational Concerns

### Rate Limiting

Total API Request count depends on the plan. Details on Rate Limiting can be found [here](https://developer.salesforce.com/docs/atlas.en-us.salesforce_app_limits_cheatsheet.meta/salesforce_app_limits_cheatsheet/salesforce_app_limits_platform_api.htm).

We can monitor the state of rate limiting on each request:
- Information returned in the `Sforce-Limit-Info` response header for REST APIs.
- Information returned in the response body (in <type>API REQUESTS</type>) for SOAP APIs.

Note that the current rate of 1 execution per minute is too frequent, since there will be no new data available for large intervals. We need a total `2 + N` API calls per run, where `N` is the number of new CSV files available for download.

### Large File Download

We can use [compression](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_rest_compression.htm#intro_rest_compression) for faster downloads.

### Checkpoints

We should probably retain the last processed record's `CreatedDate` along with file ID(s). I think this is quite safe and will lead to no duplicates, since it is unlikely to have multiple files being created the exact same time. Either way, we will retrieve records with creation date, greater or equal to the last checkpoint.

If we cannot change the polling schedule, we should also implement a sort of expiring lock so that concurrent executions are not allowed. Although CSV downloads seem quite fast in the development environment, there might be some delays for large Salesforce deployments.

## Considerations & Open Items

1. The only required input from the user is the integration account credentials.
2. I initially thought that secondary credentials should also be optional as input, in case the user wants to perform a Credential Rotation. I believe we should consider at some point, as it may apply to other source types as well.
3. In the future it may be more efficient to download the files and upload them to S3, instead of also parsing the record within the same Lambda execution.
4. Are the mentioned event types adequate for the time being? I also don't think we should have the user select event types, we can parse any of these types if they are available.

**Comment by georgepsarakis** [comment]
Maximum retention is [30 days](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/using_resources_event_log_files.htm), so this will be the default (non-configurable) backfill time window as well.

The amount of log files that need to be downloaded during the backfill process:
- Maximum of 5 log types selected.
- 1 Hourly file (could be more for highly active organizations for the `URI` type).
- 30 x 24 x 5 = 3600 files

**Comment by kostaspap** [comment]
> Maximum retention is [30 days](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/using_resources_event_log_files.htm), so this will be the default (non-configurable) backfill time window as well.
> 
> The amount of log files that need to be downloaded during the backfill process:
> 
> * Maximum of 5 log types selected.
> * 1 Hourly file (could be more for highly active organizations for the `URI` type).
> * 30 x 24 x 5 = 3600 files

Note that in general the pullers don't do a full backfill when they start, we just backfill "some" data just to demonstrate that the system is working. We shouldn't do a full backfill - for many heavy users of salesforce this could be several GBs of data all pushed through the system at once. 
While Panther should be able handle it, that might not be the case for the APIs that we are querying. Some have (often unpublished) throttling limits. We want to avoid hitting those APIs hard when we start, it could have unintended consequences. 

I agree that at some point it might be useful to be able to pull data from such endpoints on demand or even configure the default backfill period when someone onboards it. But we shouldn't hardcode the 30 days in. I think 1 hour or something shoul be enough to get us going.

**Comment by georgepsarakis** [comment]
Great, thanks for the feedback, I'll set it to 1-2 hours maximum then!

**Comment by alxarch** [comment]
> In the future it may be more efficient to download the files and upload them to S3, instead of also parsing the record within the same Lambda execution.

Pullers should not be doing any parsing. It is the first puller that we encounter that has CSV data.
Can you elaborate on the implied parsing that will be required in the puller Lambda?

**Comment by georgepsarakis** [comment]
@alxarch I understand that, but there are some small complications, because we either have to:
1. Write raw events directly to S3. In the case of CSV, if the fields differ per type, we can't mix different types together in the same S3 file, so we also need to generate separate S3 files per log type.
2. Wrap the event in a simple JSON object and perform custom "unwrapping" during log processing.

I (think I) implemented (1) in order to avoid having to define a custom, native parser and utilize managed schemas in this case too. I am definitely open to suggestions 😄 !

**Comment by alxarch** [comment]
@georgepsarakis as long as the events have some different required fields, it should be working if you strip the header

**Comment by kostaspap** [comment]
Salesforce provides us the link to download CSV files - each containing its own type. 
Why not just download these files from Salesforce and write them to S3 as is? Why do we have to mix the types as suggested in #1?

**Comment by georgepsarakis** [comment]
> Why not just download these files from Salesforce and write them to S3 as is? 

We could but we would have to bypass the `APIPuller.Run` logic and call the S3 writer instance directly I guess. We would also have to manually flush to ensure that files are not concatenated. I wasn't sure if we would want to go against the generalized puller logic, but I can certainly explore this solution further if this sounds indeed better.

We discussed it with @alxarch and returning CSV rows to `APIPuller.Run` for all event (log) types and mixing them together in a single file will work, as long as:
1. The column count is different for each CSV parser (I'll need to check if this restriction applies).
2. The header is stripped.
3. Additional support for setting a [constraint to a field to only allow specific values](https://github.com/panther-labs/panther/issues/2529#issuecomment-777633188) is added in the parser definition language.

> Salesforce puller could write each file type to different S3 prefix, the log processor would know which type corresponds to each file by looking at the prefix of the S3 files.
As far as I understand, this is not yet supported for YAML-defined parsers. I could look more into that if necessary.

**Comment by kostaspap** [comment]
> > Why not just download these files from Salesforce and write them to S3 as is?
> 
> We could but we would have to bypass the `APIPuller.Run` logic and call the S3 writer instance directly I guess. We would also have to manually flush to ensure that files are not concatenated. I wasn't sure if we would want to go against the generalized puller logic, but I can certainly explore this solution further if this sounds indeed better.
> 
> We discussed it with @alxarch and returning CSV rows to `APIPuller.Run` for all event (log) types and mixing them together in a single file will work, as long as:
> 
> 1. The column count is different for each CSV parser (I'll need to check if this restriction applies).
> 2. The header is stripped.
> 3. Additional support for setting a [constraint to a field to only allow specific values](https://github.com/panther-labs/panther/issues/2529#issuecomment-777633188) is added in the parser definition language.
> 
> > Salesforce puller could write each file type to different S3 prefix, the log processor would know which type corresponds to each file by looking at the prefix of the S3 files.
> 
> As far as I understand, this is not yet supported for YAML-defined parsers. I could look more into that if necessary.

I see what you mean. However I am afraid that we end up trying to code our way around existing interfaces that were not designed for the Salesforce puller usecase. The Okta/Slack/GSuite pullers follow their own pattern: 
- HTTP requests contain few events in the response(10s or 100s)
- The remote API makes new events available rather quickly. We checkpoint frequently on every page of events
- We have to buffer the data in the application before writing them to S3 to avoid scenarios of too many little files in S3

Salesforce doesn't have any of the above characteristics.
Salesforce is more similar to Crowdstrike puller than Okta puller. It makes new data available infrequently but in bigger batches. 

If anything, it seems we might need to create a new "category" of pullers for the likes of Crowdstrike or Salesforce. The rest of the pullers can keep their own interfaces.

**Comment by kostaspap** [comment]
Issue moved to [panther-labs/panther-enterprise #2218](https://github.com/panther-labs/panther-enterprise/issues/2218) via [**ZenHub**](https://www.zenhub.com/)
