### ISSUE TITLE
Fix rule error: AttributeError("'ImmutableList' object has no attribute 'get'") 

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther#2550]
### Describe the bug

Rule `AWS.CloudTrail.ResourceMadePublic` is reporting the following error: 

```
AttributeError("'ImmutableList' object has no attribute 'get'") 
```

### Steps to reproduce

1. Go to a Panther deployment
2. Go to Rules page, find rule `AWS.CloudTrail.ResourceMadePublic`
3. Click edit on the rule
4. Click "Run all tests" and see error

### Expected behavior

The rule should't report an error

### Environment

How are you deploying or using Panther?

- Panther version or commit: 1.15.2

**Comment by georgepsarakis** [comment]
With the introduction of the immutable event wrapper in #2350, the event nested objects are lazily converted to `ImmutableDict` / `ImmutableList` objects instead of the built-ins `dict` and `list`. The failing `panther-analysis` rule makes use of an external Python package that performs AWS policy analysis ([policyuniverse](https://github.com/Netflix-Skunkworks/policyuniverse/)).

In `panther-analysis` we use from this package:
- [`policyuniverse.policy.Policy`](https://github.com/panther-labs/panther-analysis/blob/bc8518644e0a8fc7735576a700aa7269b3257546/aws_cloudtrail_rules/aws_resource_made_public.py#L2): used in several locations, depends on [`Statement`](https://github.com/Netflix-Skunkworks/policyuniverse/blob/c653d88417573280e344f01a47c967217c5d0956/policyuniverse/statement.py).
- [`policyuniverse.expander_minimizer.expand_policy`](https://github.com/Netflix-Skunkworks/policyuniverse/blob/c653d88417573280e344f01a47c967217c5d0956/policyuniverse/expander_minimizer.py#L200): not related / affected by this issue.
- [`policyuniverse.action_categories.categories_for_actions`](https://github.com/Netflix-Skunkworks/policyuniverse/blob/c653d88417573280e344f01a47c967217c5d0956/policyuniverse/action_categories.py#L61): not related / affected by this issue.

`policyuniverse` in order to normalize certain field values, attempts to detect if the value is of type `list` and if not, create a list with the object as the only element:
- https://github.com/Netflix-Skunkworks/policyuniverse/blob/c653d88417573280e344f01a47c967217c5d0956/policyuniverse/policy.py#L32
- https://github.com/Netflix-Skunkworks/policyuniverse/blob/c653d88417573280e344f01a47c967217c5d0956/policyuniverse/statement.py#L57
- https://github.com/Netflix-Skunkworks/policyuniverse/blob/c653d88417573280e344f01a47c967217c5d0956/policyuniverse/statement.py#L73
- https://github.com/Netflix-Skunkworks/policyuniverse/blob/c653d88417573280e344f01a47c967217c5d0956/policyuniverse/statement.py#L140
- https://github.com/Netflix-Skunkworks/policyuniverse/blob/c653d88417573280e344f01a47c967217c5d0956/policyuniverse/statement.py#L218

Since we are now returning a different type, this check fails, essentially creating a list with the `ImmutableList` instance as the only element. Thus an error is raised in locations where a mapping is expected.

### Possible Solutions

We could easily bypass the issue in [`Policy`](https://github.com/Netflix-Skunkworks/policyuniverse/blob/c653d88417573280e344f01a47c967217c5d0956/policyuniverse/policy.py#L32), by creating a sub-class and overriding the constructor in order to inverse the type checking logic. We would then check for `Mapping` sub-classes, instead of `list`. The real issues start with the `Statement` class which needs closer examination, since some checks may actually lead to different code branches, causing inconsistencies instead of exceptions.

Unfortunately the most quick and robust workaround for now would be to change [aws_resource_made_public.policy_is_internet_accessible](https://github.com/panther-labs/panther-analysis/blob/bc8518644e0a8fc7735576a700aa7269b325754/aws_cloudtrail_rules/aws_resource_made_public.py#L10) to use list / dict objects. Since some objects are nested, the faster solution (in terms of implementation) is to pass the internal container to the `Policy` class:

```python
def policy_is_internet_accessible(json_policy):
    if json_policy is None:
        return False
    return Policy(json_policy._container).is_internet_accessible()
```

Alternatively we could JSON-encode / decode the `ImmutableDict` instance. As far as I understand this code branch is called only for `PutBucketPolicy` events, which should be very few in total. This way we avoid exposing protected variables / APIs and we can retain backwards compatibility a bit easier, if the versions of Panther and `panther-analysis` are not in-sync.

### Other Findings

In the process, I also found another flaw in the immutable wrappers: when [iterating over a collection](https://github.com/panther-labs/panther/blob/b763080f10329d6e61a2c74a0712625face13ae5/internal/log_analysis/rules_engine/src/immutable.py#L67) we should be ensuring that each element is immutable. This affects only lists (because iteration over mappings returns the keys) and can be easily solved by yielding each element after passing it through the `_ensure_immutable` method:

```python
>>> event = {'a': { 'd': [{'e': 1}] } }
>>> e = PantherEvent(event, None)
>>> print(list(e['a']['d']))
[{'e': 1}]
>>> print(list(e['a']['d'])[0] is event['a']['d'][0])
True
```

**Comment by kostaspap** [comment]
> Alternatively we could JSON-encode / decode the ImmutableDict instance. 

I am starting to think if that's the best approach for now? I am worried that by publishing a rule that uses `_container`, we would be encouraging people to do so - it could lead to issues down the road.

**Comment by georgepsarakis** [comment]
> I am starting to think if that's the best approach for now?

I agree, we should discourage use of any mutable objects.

Rules / policies in `panther-analysis` using `policyuniverse.policy.Policy` (not affected marked with 🆗 ):

1. https://github.com/panther-labs/panther-analysis/blob/bc8518644e0a8fc7735576a700aa7269b3257546/aws_cloudtrail_rules/aws_resource_made_public.py
2. https://github.com/panther-labs/panther-analysis/blob/bc8518644e0a8fc7735576a700aa7269b3257546/aws_iam_policies/aws_iam_inline_policy_does_not_grant_network_admin_access.py 🆗 
3. https://github.com/panther-labs/panther-analysis/blob/bc8518644e0a8fc7735576a700aa7269b3257546/aws_iam_policies/aws_iam_policy_does_not_grant_admin_access.py 🆗 
4. https://github.com/panther-labs/panther-analysis/blob/bc8518644e0a8fc7735576a700aa7269b3257546/aws_iam_policies/aws_iam_policy_does_not_grant_network_admin_access.py 🆗 
5. https://github.com/panther-labs/panther-analysis/blob/bc8518644e0a8fc7735576a700aa7269b3257546/aws_iam_policies/aws_iam_role_restricts_usage.py 🆗 
6. https://github.com/panther-labs/panther-analysis/blob/bc8518644e0a8fc7735576a700aa7269b3257546/aws_kms_policies/aws_kms_key_policy_restricts_usage.py 🆗 
7. https://github.com/panther-labs/panther-analysis/blob/bc8518644e0a8fc7735576a700aa7269b3257546/aws_s3_policies/aws_s3_bucket_policy_allow_with_not_principal.py 🆗 
8. https://github.com/panther-labs/panther-analysis/blob/bc8518644e0a8fc7735576a700aa7269b3257546/aws_s3_policies/aws_s3_bucket_principal_restrictions.py 🆗 
9. https://github.com/panther-labs/panther-analysis/blob/bc8518644e0a8fc7735576a700aa7269b3257546/aws_s3_policies/aws_s3_bucket_secure_access.py 🆗 

It seems that we only pass event data from that specific rule. A centralized helper function could be added, that constructs new `Policy` instances in a safe manner, but since there is only one location, we could also temporarily patch it there.

**Comment by nhakmiller** [comment]
I agree that the immutability shouldn't be bypassed by passing around the `_container` if we can help it. The `json.loads(json.dumps(json_policy, default=PantherEvent.json_encoder))` does not look intuitive/user friendly though, could it be possible that we add a function to our immutable event such as "to_dict" or something so we can do `Policy(event.to_dict())` or something like that? And hide away that encoding/decoding part from users. This way feels a little more usable for customers in general, and they don't have to worry about implementation details. We just tell them "hey this thing isn't actually a dictionary but mostly behaves like one. If you want to do an operation that is exactly like a dictionary, call this function to do it. But its expensive so be sparing".

**Comment by georgepsarakis** [comment]
> The json.loads(json.dumps(json_policy, default=PantherEvent.json_encoder)) does not look intuitive/user friendly though, could it be possible that we add a function to our immutable event such as to_dict or something so we can do Policy(event.to_dict()) or something like that?

Sure we could! It is actually something that we have been discussing with Kostas as well. I just mentioned this as a quick solution to possibly temporarily workaround the current production issue, without requiring a new release / deployment.

Note that I have already opened a PR on `policyuniverse`, and if this gets merged (and released) we don't have to do any special handling or conversions. We should probably implement the conversion interface either way though, in order to allow interoperability with other libraries that may have similar strict type requirements.

**Comment by georgepsarakis** [comment]
The next release of `policyuniverse` will contain the [fix](https://github.com/Netflix-Skunkworks/policyuniverse/pull/95).

**Comment by kostaspap** [comment]
> The next release of `policyuniverse` will contain the fix: [Netflix-Skunkworks/policyuniverse#95](https://github.com/Netflix-Skunkworks/policyuniverse/pull/95)

Awesome, great work @georgepsarakis !! 
I think we should still offer the `to_dict()` method on the PantherEvent, that just returns a deep copy of the `_container` as a `dict`. What do you think?

**Comment by georgepsarakis** [comment]
Thanks! I hope I got it right and didn't miss any case ... 🤔 

As far as the interface to a deep copy of the original object is concerned, I would also like to propose the use of a `.copy` method which already exists for `list` and `dict` types, but provides a shallow copy of the builtins.

So essentially we can add to the interface:
- `ImmutableList.copy -> deepcopy(self._container)`
- `ImmutableDict.copy ->  deepcopy(self._container)`
- `ImmutableDict.to_dict -> alias of .copy`

Adding a custom method has its merits, but may introduce some small learning curve. Reusing the same name for lists / dictionaries will also expose a uniform API across types. How does that sound?

**Comment by kostaspap** [comment]
> Thanks! I hope I got it right and didn't miss any case ... 🤔
> 
> As far as the interface to a deep copy of the original object is concerned, I would also like to propose the use of a `.copy` method which already exists for `list` and `dict` types, but provides a shallow copy of the builtins.
> 
> So essentially we can add to the interface:
> 
> * `ImmutableList.copy -> deepcopy(self._container)`
> * `ImmutableDict.copy ->  deepcopy(self._container)`
> * `ImmutableDict.to_dict -> alias of .copy`
> 
> Adding a custom method has its merits, but may introduce some small learning curve. Reusing the same name for lists / dictionaries will also expose a uniform API across types. How does that sound?

+1

**Comment by georgepsarakis** [comment]
Adding the full, tested workaround which should work for 1.15.x deployments:

- Go to `/detections/rules/AWS.CloudTrail.ResourceMadePublic/edit/?section=functions`
- Replace the `Rule Function` body with the following:
```python
import json
from policyuniverse.policy import Policy
from src.enriched_event import PantherEvent


# This is a helper function so that the logic determining whether this is an
# acceptable policy can be updated easily.
def policy_is_not_acceptable(json_policy):
    if json_policy is None:
        return False

    return Policy(json_policy).is_internet_accessible()


# Normally this check helps avoid overly complex functions that are doing too many things,
# but in this case we explicitly want to handle 10 different cases in 10 different ways. Any
# solution that avoids too many return statements only increases the complexity of this rule.
# pylint: disable=too-many-return-statements
def rule(event):
    parameters = event.get('requestParameters', {})

    if not parameters:
        return False
    if event.get('errorCode') == 'AccessDenied':
        return False
    # S3
    if event['eventName'] == 'PutBucketPolicy':
        # Don't alert if access is denied
        return policy_is_not_acceptable(json.loads(json.dumps(parameters.get('bucketPolicy', None), default=PantherEvent.json_encoder)))

    # ECR
    if event['eventName'] == 'SetRepositoryPolicy':
        policy = parameters.get('policyText', '{}')
        return policy_is_not_acceptable(json.loads(policy))

    # Elasticsearch
    if event['eventName'] in [
            'CreateElasticsearchDomain', 'UpdateElasticsearchDomainConfig'
    ]:
        policy = parameters.get('accessPolicies', '{}')
        return policy_is_not_acceptable(json.loads(policy))

    # KMS
    if event['eventName'] in ['CreateKey', 'PutKeyPolicy']:
        policy = parameters.get('policy', '{}')
        return policy_is_not_acceptable(json.loads(policy))

    # S3 Glacier
    if event['eventName'] == 'SetVaultAccessPolicy':
        policy = parameters.get('policy', {}).get('policy', '{}')
        return policy_is_not_acceptable(json.loads(policy))

    # SNS & SQS
    if event['eventName'] in ['SetQueueAttributes', 'CreateTopic']:
        policy = parameters.get('attributes', {}).get('Policy', '{}')
        return policy_is_not_acceptable(json.loads(policy))

    # SNS
    if event['eventName'] == 'SetTopicAttributes':
        if parameters.get('attributeName') == 'Policy':
            policy = parameters.get('attributeValue', '{}')
            return policy_is_not_acceptable(json.loads(policy))
        return False

    # SecretsManager
    if event['eventName'] == 'PutResourcePolicy':
        policy = parameters.get('resourcePolicy', '{}')
        return policy_is_not_acceptable(json.loads(policy))

    
    return False
```
- Executing `Run Test` should have a `PASS` state.

**Comment by wey-chiang** [comment]
@georgepsarakis 

> Replace the Rule Function body with the following:

Note that the posted rule function body has since changed in the master branch -- namely the default value changing from `'{}'` to `{}`

**Comment by georgepsarakis** [comment]
A new policyuniverse version has been released today. Remaining steps have been described in https://github.com/panther-labs/panther-analysis/issues/198.
