### ISSUE TITLE
[Design] Update and view managed schemas

### ISSUE THREAD

**Issue by mattthetraveler** [panther-labs/panther#2558]
### Description

As an analyst, I want to manage my schemas in the same way I manage my rules in the custom schemas page.

### RFC

[RFC](https://github.com/panther-labs/panther-enterprise/pull/1914/files?short_path=50954df#diff-50954df7fd396b14ea2c7b17c3166dd683bb062d405d90df9cd7508efba1ebaf)

### Designs

TBD

### Acceptance Criteria
  - Fix wording where needed (i.e. 'Custom Schemas' -> 'Schemas' etc)
  - Add filters to the schema listing
  - Disable editing on Managed Schemas and implement 'Clone and edit' action
  - Change the details and listing view to include 'Managed' and 'Disabled' info.
  - Add a 'Schema Updates' page in the 'Settings' section to handle schema updates.

**Comment by dimitriszoitas** [comment]
@mattthetraveler @alxarch 

I've updated and created new screens required per the RFC. You can find the screens in this miro board: https://miro.com/app/board/o9J_lUxXVeM=/

I have a couple of questions that need to be clarified:

1. Are we going to use both Schema description and Schema id?
2. Are there any fields that should be added in the creation form of the schema? For example, should we add the id? I have added a switch to disable it.
3. Ιn the details of the schema we want the following: "rules that use this schema" and "scheduled queries that use this schema". Firstly, do we mean scheduled queries or scheduled rules? And secondly, do we have both or depending on the kind of the schema (log event, scheduled query) do we display the rules or the scheduled queries?
4. What is the proper data for "An approximate min/max event time based" - I have put seconds i dont know if that makes sense
5. I will need info/more context for "The parsers that use this schema" 

thank you

**Comment by alxarch** [comment]
> I've updated and created new screens required per the RFC. You can find the screens in this miro board: https://miro.com/app/board/o9J_lUxXVeM=/
Great! I wasn't expecting this so soon!

I added some comments on the screens, mostly clarifications about field availability and relations between statuses etc.
I am glad to see the designs include the full functionality the RFC aims for.
We should coordinate with the FE team as to which parts of the Designs will be required for the MVP and the MMP. 

> 
> I have a couple of questions that need to be clarified:
> 
> 1. Are we going to use both Schema description and Schema id?
In this first iteration (MVP) of the feature we have avoided adding new fields to the records.
The schema entries currently have:
-  The the `id` (i.e. `AWS.CloudTrail`, `Custom.FooBar`)
-  The `description` text
- The `referenceURL` with an optional link to documentation about the schema.

I assume that what shows up in the screens as 'Name' will be the `id`. Having free-text names for the schema listing can only add confusion if there is no clear identifier for each record.
One possible addition for the MMP would be to also add a `shortDescription` or `title` optional field because descriptions some times tend to be very long.

> 2. Are there any fields that should be added in the creation form of the schema? For example, should we add the id? I have added a switch to disable it.

As I mentioned above, we did not add any new fields for the MVP.

> 3. Ιn the details of the schema we want the following: "rules that use this schema" and "scheduled queries that use this schema". Firstly, do we mean scheduled queries or scheduled rules? And secondly, do we have both or depending on the kind of the schema (log event, scheduled query) do we display the rules or the scheduled queries?

These are the 'wedding-cake' version of the feature in @mattthetraveler terms. We will not require this information until much later and the details are very fuzzy at the moment. Don't bother with this.

> 4. What is the proper data for "An approximate min/max event time based" - I have put seconds i dont know if that makes sense

This information is yet unavailable. The format is yet another timestsamp. It is the start/end date range for which there are stored events.

> 5. I will need info/more context for "The parsers that use this schema"

This information will be available when we decouple Parsers from Schemas and will be part of a separate issue.
As a general design approach I think the fact that the details page of each Schema record has accounted for adding related/dependent items is sufficient for now. These dependencies will usually be label to title size strings such as the label of a source, the name of a parser, the name of a rule.

> thank you

Thank _you_!

**Comment by alxarch** [comment]
Ah! I missed something important.

We need a screen to update the managed schemas from he UI.
Currently all managed schemas are updated together from one release version to a newer one.
For details of how this should work see the 'Managed Schema updates' section of the RFC.

**Comment by dimitriszoitas** [comment]
@alxarch @mattthetraveler 

Please have a look at these:

1. MVP Mockups https://miro.com/app/board/o9J_lUxXVeM=/?openComment=3074457354578231142
2. MMP/MDP Mockups https://miro.com/app/board/o9J_lUxXVeM=/?openComment=3074457354578231229

Let me know if we're ok with the MVP mockups so that we can close this issue and we can work on the MDP mockups when the time has come.

Thank you
