### ISSUE TITLE
Graceful Handling of Python Errors in Analysis Testing

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther#335]
### Describe the bug

When writing a rule in the UI editor, any runtime error generated from a test throws 500 errors and deletes all local state. This is reproducible if you are importing a library that does not exist, or any other error occurs once the Python rule/policy function executes.

### Steps to reproduce

![Screen Shot 2020-03-03 at 1.55.00 PM.png](https://images.zenhubusercontent.com/5e5006ddf054a9e90b62b812/ad148fd8-feac-4afa-a612-5f9c256e073a)

Create a fake test event, and run the tests:

![Screen Shot 2020-03-03 at 1.55.18 PM.png](https://images.zenhubusercontent.com/5e5006ddf054a9e90b62b812/6a718551-d796-4cc7-be37-c1913ca18e6d)

### Expected behavior

We should capture the output of the rules engine, and present it to the user without crashing the page.

### Environment

- Panther version or commit: v0.3.0-50-g7a636e2
- Browser: Chrome Version 80.0.3987.122 (Official Build) (64-bit)

### Additional context

None

### Screenshots

Attached above

**Comment by 3nvi** [comment]
I personally feel that this is related to the backend. If I receive a 500, I don't know whether the UI should still be usable since the server is in shock. I may need to stop the user from performing any more actions since, I'm not aware of the consequences that these actions might have. 

This 500 page is exactly how all major websites (i.e. twitter, github, facebook, etc.) handle this scenario, for the exact same reasons. 

My proposal would be to not return a 500 and just fix the underlying issue. If the issue is not an internal server error but just a typical exception, then make sure to return a 4XX code.

**Comment by kostaspap** [comment]
> 500 and just fix the underlying issue. If the issue is not an internal server error but just a typical exception, then make sure to return a 4XX code.

Yeah, 4xx should be the appropriate response here in case a rule throws an error.

**Comment by 3nvi** [comment]
Thinking about it again, I believe handling of 500 is a business decision. Perhaps we want to always show a toaster and never redirect to a page, but that will always come with the risks that I mentioned above (since currently we never manually throw a 500 intentionally).

It sometimes makes sense to send a 503 to designate that a certain service is down, but we need proper metadata (and error structure accross **all of our lambdas**) to make sure that the front-end can properly parse & understand the error thrown
