### ISSUE TITLE
Proactive Detection of Misconfigured Sources

### ISSUE THREAD

**Issue by nhakmiller** [panther-labs/panther#352]
### Description

With #341 we require all new sources and all updates to sources to be valid. But currently we don't do any sort of automatic daily health checks for existing sources. We should periodically check that all sources are still in a good state, and alert users if they are not.

### Acceptance Criteria

- Store the health status of each source
- Periodically re-check the health of each source without user interaction
  - Ideally, users should be able to manually kick off a source re-check if they want in addition to the automatic checking
- If a source starts failing, the user should be notified

**Comment by nhakmiller** [comment]
One point that was discussed and not decided on during our standup was how the user should be notified (the third bullet point of the acceptance criteria). I know @3nvi, @jacknagz , @kostaspap , and @austinbyers all had some input.

Here are a few suggestions we discussed:
- Hooking into the Cloud Security or Log Analysis (or both) alerting pipelines, and sending a High/Critical (or configurable?) severity alert.
  - Pros: hooks into existing infrastructure and destinations, flexible
  - Cons: May add some confusion/cumbersome configurations to sources.
- Hooking into the operations/monitoring workflow that @rleighton put together with CloudWatch alarms.
- Notifying users via a popup in the UI

Anyone that has any pros/cons to add to these (or completely separate ideas) please feel free to respond to this comment with those.

**Comment by austinbyers** [comment]
I know we have the little alarm bell in the upper right corner of the web app that's not actually used for anything, not sure if this is an example of what we had in mind.

I also really liked @3nvi 's suggestion to query the health checks as part of the dashboards. As for notifying users, I suppose we could re-use the same monitoring topic we have for CloudWatch alarms

**Comment by kostaspap** [comment]
I would consider this an alarm like any other for our system. It should have its description, runbook etc. 
and for that I think we should extend the existing mechanism designed by @rleighton . We tell users to check the Panther CW alerts and CW Dashboard to see Panther's health, we shouldn't divert them to some other mechanism for other parts of the system. We should have a single place to display the application health, anything else will be confusing for any Ops team to manage. 

Imo, if we decide to use the UI to display the health of Panther installation, we should do it for the full installation not for only one subsystem.

As I see it, this work can have three deliverables (not necessarily in that sequence):
- Add one/multiple CW Alarm(s) for the health of the sources.
- Connect our existing CW Alarms with the UI. If a CW Alarm is in ALARM state, the UI could display it, potentially with the Alarm's message/runbook. 
- Allow people to be notified for any Alarm using the existing Destinations instead of forcing them to plug in to the CW Alarms SNS topic. 

Regarding on how to identify if a source is in a ALARM or OK state: 
 - One way is to use some Canary (what @nhakmiller  suggested in the description). CW actually supports [Canaries](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Synthetics_Canaries.html). Using canaries for source health check is not different than canaries we would use for other healtchecks in the system (e.g. frontend healthchecks), so we might as well use a mechanism that can be extended for everything. 
 - We shouldn't just rely on canaries. We need to make sure the the same CW Alarm is triggered if Log Processor doesn't have permissions to read a bucket or compliance cannot query resources because the IAM Role is missing or doesn't have the necessary permissions. Canaries are just complementary to real-time monitoring and alerting.

**Comment by nhakmiller** [comment]
We have made (and are making) a few changes recently to how the source health is displayed in the UI. With this in mind, I think I will close this issue out. If & when it becomes a priority, we can re-open the issue or just create a new one.
