### ISSUE TITLE
CloudWatch Alarm Generation Should Resolve References

### ISSUE THREAD

**Issue by rleighton** [panther-labs/panther#435]
Currently CloudWatch alarm generation is done by parsing CloudFormation files but this parsing does not understand references (only constants). Ideally, this process should read all the CF files and resolve references.

**Comment by austinbyers** [comment]
I ran into this immediately when trying to merge #444 - CFN templates should be built statically and not require an existing deployment to generate.

References can't actually be resolved until deploy time - if you parse a file and see a `!Ref` to a parameter, you can lookup that parameter in the template but you won't know its value.

However, if those values are set in the config file, we can just read that value instead. That might be a sufficient solution.

Another option is to use parameters for lambda memory/timeout in the alarm stack instead of computing the thresholds explicitly (we used to do this). Then the threshold is computed by CFN based on the actual parameters instead of when generating the stack. You can use lists for memory and timeout to avoid the 60 parameter limit.

**Comment by austinbyers** [comment]
I was able to pretty easily read the value from the config file, that should be a sustainable solution for the foreseeable future
