### ISSUE TITLE
Move Docs Into Their Own Repo

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther#534]
### Description

To better accommodate document versions, let's move the Gitbook docs into their own repo with branches per major version.

### Acceptance Criteria

- New repo called `panther-docs-gitbook`
- Create major version branches (v1)
- Configure Github <> Gitbook syncing with the new repo

**Comment by 3nvi** [comment]
I'm not 100% sure I agree. Most of the times we want to sync changes in code with changes in docs. I don't think that we'll have a lot of dooc changes that  aren't related to a change in code (currently we have an exception due to re-organization).

The whole point of the monorepo was to consolidate as much data as possible, so we don't have to open multiple PRs

**Comment by 3nvi** [comment]
@jacknagz how do we move on?
