### ISSUE TITLE
Source Onboarding UX Improvements

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther#598]
### Description

While adding/removing/editing many cloudsec/log analysis sources, I identified a couple of UX and functionality improvements. 

### Acceptance Criteria
- **Users should be able to quickly rename a source.** Currently, users have to download templates and click all the way through just to fix a typo.
- **Users should not be blocked to download/run CloudFormation to add a source.** They should be able to click through to the validation because sometimes roles are created out of band with either Terraform or with nested stacks.
- S3 bucket names should be [validated](https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html) to prevent ARNs from accidentally being pasted in the field.

**Comment by 3nvi** [comment]
>Users should be able to quickly rename a source. Currently, users have to download templates and click all the way through just to fix a typo.

This is intentional. In Log Onboarding, if a user renames a resource, then a IAM Role needs to be altered as well. We link rolesNames with integrationNames. CloudSec doesn't have this dependency, but it follows log-onboarding's example for consistency. I don't know if we can/should use bucket name  for this. @kostaspap?

> Users should not be blocked to download/run CloudFormation to add a source. They should be able to click through to the validation because sometimes roles are created out of band with either Terraform or with nested stacks.

This actually takes me by surprise, since we presented & validated all the requirements from an Analyst's perspective with @nhakmiller and @kostaspap . This is not a simple to do, since we investigated multiple alternative flows, before coming to a conclusion to do it like that. If we deviate from the way it is right now, we are not allowing the user to know when a source is ready. 

To achieve this we need to create other mechanisms in place like:

- Prompts that will say to the user that something is misconfigured
- Ability to re-run a health check
- Ability to download the related cloudformation template or launch the console after the resource has been added
- Alter the save mechanism to not perform a health check prior to saving

> S3 bucket names should be validated to prevent ARNs from accidentally being pasted in the field.
Should I translate this to "If the user adds an ARN we should tell him that we just need the bucket name"? If not, then can you elaborate?

**Comment by kostaspap** [comment]
> Users should be able to quickly rename a source. Currently, users have to download templates and click all the way through just to fix a typo.


According to current design, the Label of a source is used as the IAM Role suffix, so changing the label requires updates in the IAM role. Label is not just a friendly name, but also a label for the IAM Role created in the user account.

**Comment by kostaspap** [comment]
> This actually takes me by surprise, since we presented & validated all the requirements from an Analyst's perspective with @nhakmiller and @kostaspap . This is not a simple to do, since we investigated multiple alternative flows, before coming to a conclusion to do it like that. If we deviate from the way it is right now, we are not allowing the user to know when a source is ready.

@3nvi  I actually think that @jacknagz  doesn't request that we skip the healthchecks. He is referring to the fact that currently, to proceed from the 2nd page of the onboarding flow to the 3rd page, someone has to either click the Download or the Launch stack button. The "Next" button remains greyed-out otherwise. I think this should be a simple change for the UI - and I also agree that I found many times myself having to "fake" download a template to proceed through the screens since I had deployed the template out of sync.

**Comment by 3nvi** [comment]
> @3nvi I actually think that @jacknagz doesn't request that we skip the healthchecks. He is referring to the fact that currently, to proceed from the 2nd page of the onboarding flow to the 3rd page, someone has to either click the Download or the Launch stack button. The "Next" button remains greyed-out otherwise. I think this should be a simple change for the UI - and I also agree that I found many times myself having to "fake" download a template to proceed through the screens since I had deployed the template out of sync.

You forget that if you "skip" it, then the final "save" will fail. This is because "save" performs a health check. If you skip it, then you will face problems when saving later on. 

@jacknagz If you just meant that the "next" button should be enabled by default (and nothing more), then I misunderstood. That's an easy fix.

**Comment by nhakmiller** [comment]
> @jacknagz If you just meant that the "next" button should be enabled by default (and nothing more), then I misunderstood. That's an easy fix.

Right, I think the idea is still perform the final health check because we want to verify that, but if they already downloaded the template in the past or decided to write their own templates that meet the minimum requirements we have but with additional stuff then we don't force them to download a template.

I suppose we could add a third button that says "I've already deployed this stack" so users have to explicitly acknowledge that they did some out of band work, and the button would just serve to unlock the next button.

**Comment by 3nvi** [comment]
> Right, I think the idea is still perform the final health check because we want to verify that

I just wanna make sure that this is still the case

**Comment by 3nvi** [comment]
@jacknagz can we get some feedback on that?

**Comment by jacknagz** [comment]
> Right, I think the idea is still to perform the final health check because we want to verify that

Correct!

**Comment by 3nvi** [comment]
@jacknagz Thanks for the replies, before I move on to create a task out of the issue, can you please give me an answer here?

>>S3 bucket names should be validated to prevent ARNs from accidentally being pasted in the field.

>Should I translate this to "If the user adds an ARN we should tell him that we just need the bucket name"? If not, then can you elaborate?

**Comment by nhakmiller** [comment]
From the docs:

`The bucket name can be between 3 and 63 characters long, and can contain only lower-case characters, numbers, periods, and dashes.`

So for one you could just validate there are no colons, which are not valid as part of s3 bucket names but might indicate someone accidentally put in an ARN.

https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-s3-bucket-naming-requirements.html

**Comment by 3nvi** [comment]
The criteria of this issue then will change to

- Users should not be blocked to download/run CloudFormation to add a source. They should be able to click through to the validation because sometimes roles are created out of band with either Terraform or with nested stacks.

- S3 bucket names should be validated to prevent ARNs from accidentally being pasted in the field.
