### ISSUE TITLE
[Proposal] Enhance Cognito security with remembered devices

### ISSUE THREAD

**Issue by 3nvi** [panther-labs/panther#606]
### Describe the ideal solution

We can add an additional level of security by forcing Cognito to remember the user's logged-in devices. Each time a user signs-in for the first-time using a new device, this device will be remembered by Cognito.

If a user has his/her JWT token stolen by a malicious actor who tries to use them **on a different device,** Cognito will block the request as it will see that the JWT is sent from an untrusted device.

### Describe your use cases

Everyday login

### How frequently would you use such feature

Daily

### Describe alternatives you have considered

It's just an additional layer of security.

### References

 https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-device-tracking.html

https://aws.amazon.com/blogs/mobile/tracking-and-remembering-devices-using-amazon-cognito-your-user-pools/

### Additional context

Unfortunately, this is not supported through Cloudformation. 

It can also be couple with advanced security mode (report publicly exploited creds): https://aws.amazon.com/blogs/security/how-to-use-new-advanced-security-features-for-amazon-cognito-user-pools/

**Comment by austinbyers** [comment]
Good idea, thanks for the context!

Enabling remembered devices and advanced security features both seem like simple Cognito API calls. We already have to do some manual setup of the user pool that CloudFormation does not support (TOTP enforcement)

Cognito advanced security has a [higher cost](https://aws.amazon.com/cognito/pricing/), but most deployments will likely not have more than a few dozen users so the cost should be negligible

**Comment by nhakmiller** [comment]
What would be the process of verifying a new device? Just an email notification? I think it's a nice touch, especially for a security product.

**Comment by austinbyers** [comment]
Based on the documentation, I don't think anything changes at all for the user. Cognito just silently remembers their device ID to prevent the attack Aggelos described above: if an attacker steals your session token, Cognito will reject the request because the device IDs don't match.

Cognito does allow us to use remembered devices in place of MFA (but I don't think we should). 

I'll test this of course, but I think it's literally just two API calls in the deploy process

**Comment by 3nvi** [comment]
>Based on the documentation, I don't think anything changes at all for the user. Cognito just silently remembers their device ID to prevent the attack Aggelos described above: if an attacker steals your session token, Cognito will reject the request because the device IDs don't match.

Exactly this

**Comment by 3nvi** [comment]
>I'll test this of course, but I think it's literally just two API calls in the deploy process

@austinbyers Thanks for taking the time to fully review this

**Comment by austinbyers** [comment]
I put up a PR for enabling advanced security, but I'm not adding remembered devices yet:

If you enable remembered devices with CloudFormation, it also enables "skip MFA for remembered devices". I don't see any way to disable that setting from CFN nor from the Go SDK. When that setting is on, logins to the panther app fail (presumably because it tries to ask for a 2-factor code, but Cognito doesn't need one for remembered devices)

Remembered devices are more a convenient alternate form of MFA rather than additional security on top of MFA. The device key is only checked during user sign-in, I'm not sure it actually protects against the attack you describe.

I'm going to leave this issue open because we could implement "remembered devices" the way they are intended: add a "remember this device" checkbox on sign-in that will allow the user to disable MFA on devices that have already logged in before

**Comment by 3nvi** [comment]
> If you enable remembered devices with CloudFormation, it also enables "skip MFA for remembered devices"

@austinbyers That sounds weird. Doesn't this doc contradict what you are saying https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-device-tracking.html?

You are 100% right that we **never want to disable MFA**, but I feel that this is optional and not enforced when we are tracking devices. What am I missing?

**Comment by austinbyers** [comment]
> You are 100% right that we never want to disable MFA, but I feel that this is optional and not enforced when we are tracking devices.

(a) _Remembered devices_ and (b) _optional MFA for remembered devices_ are two different settings. You can have (a) without (b). So the question is - do we want both?

If yes - we want MFA to be optional for recognized devices:

1. The Panther login flow does not work at all right now with those settings, I tried. You can enter your password, then instead of seeing the MFA page, you get redirected back to the login page again. So something would have to change in the frontend for this to work
2. We should explicitly expose this feature as a checkbox on the login page: "remember this device?" This is very standard practice - we shouldn't remember *every* device in case someone is logging in from a shared computer

If no - we want to remember devices but still always require MFA:

1. Why? We're tracking devices but not using them for anything. Users may be concerned when they realize their Panther deployment is silently tracking their devices
2. This is not possible to implement in CloudFormation, and it's not clear whether it's possible from the Go SDK. CFN is actually pretty bad with Cognito user pools - we have to enable MFA via API call, for example, because CFN forces SMS for MFA. You're right, CloudFormation's implementation does not match the documentation

**Comment by 3nvi** [comment]
For compliance reasons, we always want to have MFA required. My recommendation was to add remembered devices on top of a Required MFA. After your last comment I understand that the engineering effort involved will not yield any clear benefits, thus I'm gonna close this issue
