### ISSUE TITLE
Show Alert Title in Alert Tables

### ISSUE THREAD

**Issue by 3nvi** [panther-labs/panther#615]
### Description

This ticket makes sure to add the `Alert Title` in all the alert tables found throughout the application. Alert Title is a prominent thing and should be added as the first column in all related tables

### Acceptance Criteria

In the RuleDetails page, the alerts should:

- Add alert title to schema (`AlertSummary` and `AlertDetails`)
- Add the alert title as the first column in the table found in RuleDetails page
- Add the alert title as first column in the ListAlerts page
- Show the dedup string in the table found in RuleDetails page

**Comment by kostaspap** [comment]
This requires backend changes - the backend doesn't return the alert title. I would recommend making an epic for this and adding all the necessary backend changes that you require.

**Comment by kostaspap** [comment]
The more I was working on this task, the more I am thinking that we might want to display something slightly different...
### List Alerts Page ###

I am thinking we should display 
1. Alert Title. This is aligned with the initial suggestion in this issue. Be aware that alert title can be potentially a pretty long string so we need to display only the first X characters. I will let UI guys decided how many characters makes sense to display
2. Rule. This is the Rule Display Name if it exists (returned by the Alerts API) or Rule ID otherwise. This is similar to what is displayed in the List Rules (`/log-analysis/rules/`) page. 
3. Severity (thinking might be better to move "earlier" since it is actually more important field IMO than the following ones)
4. Number of events (maybe just rename from existing?)
5. Created At (as is now)
6. Last matched at (as is now)

So, i think we can skip display the "dedupString" in the List Alerts page. This is a string meant to be consumed by the system and is not necessarily intended for "human" consumption.  The Alert Title actually can include all necessary information about an alert that the author of the rule meant to display. 
The following screenshot is from current solution, I don't it is easy to see that the dedup string is indeed not intended for "easy" consumption by the users. 

<img width="1243" alt="Screen Shot 2020-04-06 at 12 28 56 PM" src="https://user-images.githubusercontent.com/2652630/78553378-6ef7e500-7809-11ea-9d8b-0178f6ed89a9.png">


### Rule Details Page ###
I am thinking we should display the following columns:
1. Alert Title. See similar comments above
2. Created At
3. Last Matched At. 

Makes sense @jacknagz @3nvi ?

**Comment by kostaspap** [comment]
@jacknagz What should be the default alert title in case user hasn't specified `title` method in their Python rules? 
What should be the default title if they have specified one - should it be just the title they specified or should we put any prefix/suffix?

**Comment by jacknagz** [comment]
@kostaspap 

The one edit I'd say is this:
* We should display the `RuleID` in the ListAlerts page for your #2 item
* If the `title()` isn't specified, we fall back to the rule's `DisplayName`, which is most of the time very similarly phrased

**Comment by 3nvi** [comment]
That's easy for us. We'll display whatever you think makes more sense from an analyst's perspective. @alexmylonas can you  confirm that what @kostaspap is possible with our current schema?

**Comment by kostaspap** [comment]
> * If the `title()` isn't specified, we fall back to the rule's `DisplayName`, which is most of the time very similarly phrased

@jacknagz The DisplayName is optional. We probably don't want to display empty string... I could display the RuleID when no DisplayName is specified, but then by default for many alerts the first two columns will populated in both cases with the RuleID. Maybe that's not so horrible, but I wanted to point this out.

**Comment by kostaspap** [comment]
After some discussion with @jacknagz and @nhakmiller came up with the following ideas: 
### Introducing "short" Alert ID version ###
This will be similar to short commit hash that Github is using. It is basically the first 7 digits of the Alert ID

### Fields in Alert List page ###
Title, Created At, Severity, Short Alert ID, Event Count, Last Matched At

### Proposed Alert Details change ###
- Use Short Alert ID rather than the full Alert ID in the top
- Alert Title should be the the first field in the "Alert Details"
- Keep display the Alert ID but rename from ID => Full Alert ID
- Add "Last Matched At" field

### Alert Details section ###
Currently it has just the AlertID and the Created At column. It should instead have: 
Title, Created At, Short Alert ID, Event Count, Last Matched At

**Comment by 3nvi** [comment]
@alexmylonas you ok with that?
