### ISSUE TITLE
Editing the Source refers to a non existing stack - Log Analysis

### ISSUE THREAD

**Issue by alexmylonas** [panther-labs/panther#640]
### Describe the bug

As user I want to edit the initial Source, when I am prompted to upload a template the stack displayed name doesn't exist on AWS.

Check screenshot

### Steps to reproduce

1. Go to `Sources` pages on `Log Analysis`
2. Click on `Edit` the initial Source
3. Make a small change i.e name
4. Click `Next`
5. You are instructed to upload a template to a stack that doesn't exist

### Expected behavior

I am expecting for the instructions to refer me to an existing stack that I can update

### Environment

How are you deploying or using Panther?

- Panther version or commit: 5c032b0c582a598d6dad9a86eef52dc2ef687857

### Screenshots
![Screenshot 2020-04-02 at 3.16.24 PM.png](https://images.zenhubusercontent.com/5e4fb724a541ae524a4864cc/d616cfa7-c10c-4024-aed3-bd2dd92f8802)

**Comment by alexmylonas** [comment]
The issue is described mostly from the frontend perspective, feel free to add more info for the backend affecting this! @kostaspap @austinbyers @nhakmiller

**Comment by nhakmiller** [comment]
This is because we follow a different methodology for naming the first "self onboarding" stack than we follow for future onboarding stacks.

We could either update this so it displays the correct name for the self-onboarded stack, change the self-onboarded stack to follow the same pattern as future onboarded stacks, or perhaps disallow editing of the self onboard stack.

Displaying the correct name is difficult first of all because it's randomly generated, and second of all because then we would have to have some way of differentiating the self onboard stack from the rest.

Changing the self-onboarded stack to follow the same pattern as the others would require us to change how we do the self-onboarding flow (e.g. not do it as a nested stack), but I don't think that would be too difficult and removes any other special logic.

Disallowing editing the self-onboarding stack seems like a not very good idea, but it may be the simplest to do.

**Comment by austinbyers** [comment]
The [onboarding stack](https://github.com/panther-labs/panther/blob/master/deployments/onboard.yml) contains two nested stacks with IAM roles, which is why we don't know their names

I believe @rleighton and/or @kostaspap suggested we just deploy those nested stacks directly, in which case their stack names would be known. That is a fairly easy change, although we have to do it in a way that is compatible with existing v1 deployments

**Comment by alexmylonas** [comment]
Is there an easy way to identify a stack as "self-onboarded" and then disable edit for that? Seems like the cleaner solution if I understand correclty.

**Comment by nhakmiller** [comment]
Right now we don't store that info in the backend Alex, but we could store it somewhere. Or we could keep it as an environment/build variable for the frontend.

I like Austin's suggestion though, if we can get the self onboarded stack to be treated exactly the same as every other stack that would be ideal to me.

**Comment by 3nvi** [comment]
@kostaspap can you help with that? I feel that this should be resolved from your side, since you are the ones that name the automatically deployed log stack (same with cloud security)

**Comment by 3nvi** [comment]
@rleighton can you perhaps help us as well?

**Comment by rleighton** [comment]
Hmmm. We can change how we do the stacks, but I really think allowing edits of the self-onboarding stacks is wrong because the control is supposed to be in panther_config.yml. If we were to disallow changing those, then this is a non-issue anyway. We could add a "readonly" attr to ddb and then disable editing if set. Certainly when we do SaaS, we do not want customers editing these stacks, so this might be a good approach and might apply to other stacks in the future SaaS world.

**Comment by rleighton** [comment]
I'm going to use this opportunity to keep pushing that we take these screens completely out of the UI which makes this go away: https://panther-labs.atlassian.net/wiki/spaces/EN/pages/299434109/On+Why+We+Need+To+Remove+Public+S3+Bucket+Usage

**Comment by 3nvi** [comment]
We shouldn't treat our sources differently than typical sources. We follow the example of pre-created roles in panther-enterprise.

The solution is easy, we just need to align the naming of the stacks. From my understanding, only the auto-generated ones have different stack & display names. If we align them, the problem is solved. No?

**Comment by rleighton** [comment]
I'm fine with re-naming the stacks, but I think it is mistake to allow users to edit them  directly because then the panther_config.yml and the stack are inconsistent. Could lead to support calls.

**Comment by kostaspap** [comment]
I agree with the above, makes sense to rename/re-organize the stacks to follow our standard practice. As a follow up it we could disable them if needed, note though that the `panther-config.yml` now only applies during the first deployment so for example the users can disable the self-monitoring stack only through the UI.

**Comment by rleighton** [comment]
But I can turn on / off CT and GD in panther_config.yml, that takes effect on each deploy, right?

**Comment by kostaspap** [comment]
> But I can turn on / off CT and GD in panther_config.yml, that takes effect on each deploy, right?

I'm looking at the code. Let's say someone disables "Self Onboard". The code that I see executing is this: https://github.com/panther-labs/panther/blob/5a5515e3654d8579f82db256a61300ea083bf1ee/tools/mage/deploy.go#L442-L447

Basically it will just skip updating the self-onboarding stacks but will not destroy them. 

Nevertheless, I personally am not 100% sure that we should treat Panther's self-monitoring any differently than any other monitoring. Monitoring Panther is not necessarily more critical or important than monitoring any other resource in the customer's account. I don't see why a Panther Administrator couldn't update this log processing if they wanted to - and they would need to redeploy the full Panther (with any risks that might entail) in order to e.g. update an S3 bucket.

**Comment by rleighton** [comment]
I agree, I just want them to edit in a consistent way. Forget enable/disable, I'm talking about changes. If they change the stack to not have GD but it is on in panther_config.yml they are inconsistent. I think we should using 1 "door" for all of this that uses an API. We may want to revisit all of this in the SaaS world.

**Comment by rleighton** [comment]
Anyway, as I said, I'm fine with making separate stacks to fix this particular issue. There is a larger issue of managing onboarding, but that is another conversation. I'm just using this time to remind everyone about all the warts this process currently has.

**Comment by 3nvi** [comment]
Great, so, If you're not opposed to it, I'm adding you as the sole assignee of the issue
