### ISSUE TITLE
[parsers] Retain original timestamp format for log entries

### ISSUE THREAD

**Issue by alxarch** [panther-labs/panther#836]
### Describe the ideal solution

Currently parsers convert all timestamps in a log entry to UTC and store them to Athena in a different form than the one passed in the log entry. For example timestamps that in input JSON are `float64` representing Unix milliseconds epoch are converted to `string` fields in the output. It is my understanding that this happens because of query requirements on Athena. OTOH this is in conflict with the general policy of retaining exact input log format for auditing purposes.
An ideal solution to this would be to at least retain the original log format in some form *and* provide a way to query logs based on normalized UTC timestamp values.

### Describe your use cases

Handling timestamp input transparently would allow introspection of log entry information that is lost during the parsing such as timezone information on input timestamps.

### Describe alternatives you have considered

One method would be to store timestamps as structs that keep both values in different fields with the appropriate JSON unmarshaling methods. For example:
```go
type TimestampUnix struct {
   UTC time.Time `json:"utc"`
   Raw int64 `json:"raw"`
}
```
Another solution would be to retain original input for all fields in the log entry and use normalized UTC values *only* for `p_event_time` and `p_parse_time` meta fields added by the log processing.

**Comment by rleighton** [comment]
The history behind the decision to standardize the timestamp format predates the `p_` fields. We did not do the timestamp transform and all timestamps were strings. This meant SQL users had to always use date functions for operations PER data source because the formats were different. Event time being so important this was a miserable experience. Users needed to know formats and comparing 2 datasets by time was ugly and compute expensive.

Perhaps we should have added `p_event_time` then but we did not because it seemed to me (my fault this decision) that users expect timestamps in a database to be timestamps and not strings. They want to do date operations like BETWEEN. Imagine other date fields that are common like 'createTime', 'updateTime', etc. Having those as strings is really annoying. 

Pivoting to UTC is also critical to allow data to be compared easily.

So, while we do "change original data" , which is a no-no, I think timestamps are more subtle case. I would argue we are not "changing" original data, rather just reformatting.  I fully expect in the future for some of our log sources to be binary. For example, parquet, avero and protobuf are popular serialization formats. We use JSON as an intermediate format. We would convert these sources to JSON in our system, taking binary numbers and timestamps and converting them to a textual representation. I think of what we do by standardizing the format of timestamps as similar, yet still in the realm of text.

If we were to change this decision (and we can if there is a good reason), we will need data migration code to re-process all our current customers data.

**Comment by alxarch** [comment]
TBH the only use case for the original format I could think of would be to keep time zone information to be used in rules. I don't know how useful that would be. I will close the issue for now and we can revisit if such a requirement ever comes up in a real scenario.
