### ISSUE TITLE
Improvements for Global Python Module

### ISSUE THREAD

**Issue by alexmylonas** [panther-labs/panther#855]
### Description
Currently, the module is viewable/editable by navigating through the `Settings` menu. We also have a link on Policy/Rule details that opens the module on a new tab. This is happening because if we open the link on the same page, users will lose all their changes.

### Acceptance Criteria
- Don't open a new tab for global module but redirect in the same page.
- When a user leave a Policy/Rule form, save data on sessionStorage that way when the user comes back to the same Policy/Rule sees the changes that he hasn't yet saved.

**Comment by nhakmiller** [comment]
From our conversation this morning I'll tack on some details for how point 3 could be implemented.

What we'll want is a backend service written in python that can import the global helpers and then enumerate their classes and functions with something like `dir`, then map those results into a JSON object and send them back. Since globals are only updated occasionally, this object could be stored in dynamo/s3 and when the globals are updated it gets re-created, that way when the frontend wants it it's pretty quick to retrieve and doesn't need to be generated each time.

**Comment by 3nvi** [comment]
Yeah, I like that. It's just that, normally, If a user adds a variable in the global module, they expect to see autocomplete right away.

This may not happen if the parsing is done asynchronously as a job. Can we guarantee "almost real-time" updates to this S3 when the globals are updated?

**Comment by 3nvi** [comment]
Porting bullet 3 to https://github.com/panther-labs/panther/issues/911

**Comment by nhakmiller** [comment]
> This may not happen if the parsing is done asynchronously as a job. Can we guarantee "almost real-time" updates to this S3 when the globals are updated?

It'll be around 30 seconds if I had to guess. Building the new layer takes some time, and we have to wait for that to complete before we can update the schema.
