### ISSUE TITLE
Implementation of "getIntegrationById" endpoint

### ISSUE THREAD

**Issue by alexmylonas** [panther-labs/panther#874]
### Describe the ideal solution

We need a new endpoint that functions as `getIntegrationById` endpoint.

### Describe your use cases

We currently fetching all integration via appsync (or more specifically a sub-category of integrations based on `integrationType`)  and iterate until we find one that matches the `integrationId` passed. 

### How frequently would you use such feature

Although, we are using this constantly, changes that are affected are estimated to `Monthly`

### Describe alternatives you have considered

Best alternative already implemented :)

**Comment by kostaspap** [comment]
I think a right signature could just be `GetIntegration(id string)`

**Comment by austinbyers** [comment]
This is a quick fix, but also not high priority - since there will never be more than a handful of integrations, looping over all them is awkward but the inefficiency will hardly make a difference.

Definitely something we should do, though! This is a good issue for first-time contributors, so I'm unassigning from myself. @kostaspap is also essentially the owner of this service.
