### ISSUE TITLE
[Enhancement] Dockerfile for CI is using Debian oldstable instead of stable

### ISSUE THREAD

**Issue by sagium** [panther-labs/panther#936]
### Describe the ideal solution

Since Debian has released Buster (current stable, initial release July 6th, 2019) it is recommended to use this version instead of Stretch (oldstable, initial release June 17th, 2017).

To give a simple example, this is the current state of apt and in Sid/Buster/Stretch

**Package apt**
```
sid (unstable) (admin): commandline package manager
2.1.4: alpha amd64 arm64 armel armhf hppa i386 m68k mips64el mipsel ppc64 ppc64el riscv64 s390x sh4 sparc64 x32

buster (stable) (admin): commandline package manager
1.8.2.1 [security]: amd64 arm64 armel armhf i386 mips mips64el mipsel ppc64el s390x

stretch (oldstable) (admin): commandline package manager
1.4.10 [security]: amd64 arm64 armel armhf i386 mips mips64el mipsel ppc64el s390x
```
Since Debian stable is always stable by definition, there is no need to use oldstable in terms of stability. I don't know if you follow Debian closely but the stable versions already are way behind
the latest package versions. This is why they are super stable.

Tagging @austinbyers since he seems like the Maintainer based on commits.

### Describe your use cases

This can be used for deployments, CI and development.

### How frequently would you use such feature

This image can be very useful for development as it creates an identical local environment across teammates. As long as the docker user is using the current OS user(UID:GID) and not root (docker default user). This is not required for Docker on OSX but it's required on Linux.

Right now for example, all mage builds are being run by root and not by the actual linux user executing the command. So you end up with [node_modules, .setup, .terraform, out] paths owned by root:root.

### Describe alternatives you have considered

Nice base images to consider
https://hub.docker.com/_/debian?tab=tags&page=1&name=buster

It's a good practice to use "slim" images so by adding only the necessary packages
you end up with a small image. Right now the image is quite large

```
$ docker images | grep pantherlabs
pantherlabs/panther-development-pack   1.1.2   9c2e0860d978   5 weeks ago   1.94GB
```

### References

You can check the Debian release lifecycle here.
https://www.debian.org/releases/

**Comment by 3nvi** [comment]
Hey @sagium thanks for the detailed issue.

We originally opted for stretch instead of buster because of some issues we had with the versions of Golang, NodeJS and Python that we were using (I honestly don't exactly remember what). I'd be happy to bump it to buster and see if the current development environment works with it, especially given the fact that we recently bumped some of our language dependencies. 

With regards to the root owner, you are right, that's one of the things that must have slipped us. I'll try and fix it.

I'll update  you on the status of the ticket within the next week.

**Comment by austinbyers** [comment]
Thanks @3nvi ! While you're at it, please bump Go to the [latest version](https://golang.org/doc/devel/release.html) as well (1.14.3)

**Comment by 3nvi** [comment]
Hey @sagium , just wanted to send you an update on the ticket.

Made some modifications and managed to implement our dev environment using `debian:buster`. Currently we are using [`buster-scm`](https://github.com/docker-library/buildpack-deps/blob/f84f6184d79f2cb7ab94c365ac4f47915e7ca2a8/debian/buster/scm/Dockerfile) which is basically a `debian:buster` with the addition of Networking & VCS libraries. The related PR can be found [here](https://github.com/panther-labs/panther/pull/959)

> It's a good practice to use "slim" images so by adding only the necessary packages

We've always done that. If you take a look at our Dockerfile, you'll see that we only have what's needed, it's just that the things that are needed are a lot. For example, we add `docker` to our image since we use "docker-in-docker" for building of personalized web server images. In addition, we include `aws-cli` which (as known) is a bit ridiculous size-wise, but unfortunately there are no alternatives on that.

With regards to deployment, we are actively working to port our deployment to AWS SAR, so only people that want to actively contribute to the project (not the ones that are just using it) will have to download our docker images. Perhaps that will partially mitigate the fact that they are big.

**Comment by austinbyers** [comment]
> In addition, we include aws-cli which (as known) is a bit ridiculous size-wise, but unfortunately there are no alternatives on that.

Actually, @3nvi the aws-cli hasn't been used for deployment for awhile, we could remove it if you want. It's certainly helpful for troubleshooting, configuring credentials, etc, so we may want to keep it for generic utility. But it's not required for Panther itself

**Comment by sagium** [comment]
Thanks @3nvi.

By "slim" images I meant *-slim. If you check [buildpack-deps:buster-scm](https://github.com/docker-library/buildpack-deps/tree/master/debian/buster) inheritance tree you will find the following chain

- `FROM debian:buster`
  - `FROM buildpack-deps:buster-curl`
    - `FROM buildpack-deps:buster-scm`

`debian:buster` image is about 45 MB (compressed) / 114 MB (actual size)
`debian:buster-slim` image is about 25 MB (compressed) / 70 MB (actual size)
`buildpack-deps:buster-scm` image is about 120 MB (compressed) / 294 MB (actual size)

But since your dependencies are so big, it doesn't make much difference on size to use a slim image as your base to remove only a small fraction.

The only thing that wasn't addressed by the PR is the `root:root` files generating on the build process. Unfortunately, this has only one proper fix as far as I know. Creating the current user, running the dev.sh on a new layer on top of your image and have this user to run everything.

You can do this either on [docker run](https://docs.docker.com/engine/reference/run/#user) or by adding [USER user](https://docs.docker.com/engine/reference/builder/#user) on the Dockerfile. 

I always prefer to use the `USER` in the Dockerfile's end after I'm done with installations etc.. It's tedious to use the `--user` flag in `docker run` and also if you want to actually develop using this image you will have to change files on your mounted project (not as root).

But again this is quite internal, in terms of development per project. If you don't plan to use this image for development or you don't mind doing a `sudo rm -rf` on the generated folders by `dev.sh`.

**I think the most important fix was the Debian version (as stated in the issue title), all the rest are just suggestions.**

**Comment by 3nvi** [comment]
Hey @sagium thanks for your detailed response. Took a while to reply cause I was caught up with some other tasks.

Adding a  user indeed is as simple as `-u $(id -u ${USER})`, but that would create issues with existing dependencies. Based on my understanding, users that have already installed deps under a root account won't be able to modify the related folders. Thus, users will be forced to delete  and re-install all local deps (as you pointed out). Currently, since we are aiming at making the OSS installation experience as good as it can be, this  would create some issues.

If you have an easy workaround for that let us know, else we'll have to skip that until other installation methods become the default ones (~ few weeks time)
